import type {
  FeatureRequest,
  RoadmapItem,
  QuarterlyPlan,
  QuarterlyGoal,
} from "@/types";
import { makeQuarterRef } from "./constants";

const Q2_2026 = makeQuarterRef(2026, 2);

// ── Feature Requests (Inbox) ───────────────

export const SEED_REQUESTS: FeatureRequest[] = [
  {
    id: "req_001",
    teamId: "team_navigators",
    title: "Bulk status update for feature requests",
    description: "PMs need to triage 50+ items at once. Currently requires clicking each row individually.",
    businessContext: "Saves ~2 hours per planning cycle",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["triage", "bulk-actions", "inbox"],
    productArea: "Core Product",
    goalIds: ["goal_001"],
    submittedBy: "Sarah K.",
    submittedAt: "2026-05-20T09:00:00Z",
    votes: [
      { stakeholderId: "u_2", stakeholderName: "Marcus T.", comment: "Critical for our workflow", votedAt: "2026-05-21T10:00:00Z" },
      { stakeholderId: "u_3", stakeholderName: "Priya N.", comment: null, votedAt: "2026-05-21T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_002",
    teamId: "team_navigators",
    title: "WSJF scoring framework support",
    description: "Our team uses Weighted Shortest Job First for hardware-adjacent roadmap items. RICE doesn't map well.",
    businessContext: "Unblocks 3 PMs who currently maintain separate spreadsheets",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["scoring", "frameworks", "wsjf"],
    productArea: "Core Product",
    goalIds: ["goal_001"],
    submittedBy: "James R.",
    submittedAt: "2026-05-18T11:30:00Z",
    votes: [
      { stakeholderId: "u_4", stakeholderName: "Anita L.", comment: "Already on the roadmap?", votedAt: "2026-05-19T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_003",
    teamId: "team_navigators",
    title: "Shareable read-only roadmap view",
    description: "Need to send a polished roadmap link to leadership without giving them edit access.",
    businessContext: "Eliminates the quarterly slide deck rebuild",
    source: "leadership",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["roadmap", "sharing", "stakeholders"],
    productArea: "Roadmap Planning",
    goalIds: ["goal_002"],
    submittedBy: "VP Product",
    submittedAt: "2026-05-15T08:00:00Z",
    votes: [
      { stakeholderId: "u_5", stakeholderName: "Tomás V.", comment: "Would save our leadership prep", votedAt: "2026-05-16T10:00:00Z" },
      { stakeholderId: "u_6", stakeholderName: "Hana M.", comment: "Yes please", votedAt: "2026-05-16T11:00:00Z" },
      { stakeholderId: "u_7", stakeholderName: "David P.", comment: null, votedAt: "2026-05-17T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_004",
    teamId: "team_navigators",
    title: "Linear integration — push initiatives as projects",
    description: "After approving the plan, we manually recreate everything in Linear. One-click push would save hours.",
    businessContext: "~4 hours saved per planning cycle per PM",
    source: "internal",
    prioritySignal: "critical",
    status: "new",
    tags: ["integrations", "linear", "automation"],
    productArea: "Integrations",
    goalIds: ["goal_003"],
    submittedBy: "Eng Lead",
    submittedAt: "2026-05-22T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_005",
    teamId: "team_navigators",
    title: "Capacity bar in roadmap view",
    description: "We keep over-committing. A visual capacity meter that updates as items are added would prevent this.",
    businessContext: "Prevents over-commitment before plan is locked",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["roadmap", "capacity", "planning"],
    productArea: "Roadmap Planning",
    goalIds: ["goal_002"],
    submittedBy: "Alex Chen",
    submittedAt: "2026-05-23T09:00:00Z",
    votes: [
      { stakeholderId: "u_8", stakeholderName: "Lena B.", comment: "Essential", votedAt: "2026-05-23T10:30:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_006",
    teamId: "team_navigators",
    title: "Email digest for voting round outcomes",
    description: "PMs should receive a summary when a voting round closes, not have to manually check.",
    businessContext: "Reduces time lost to manual follow-up",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "archived",
    tags: ["notifications", "email", "voting"],
    productArea: "Notifications",
    goalIds: [],
    submittedBy: "Priya N.",
    submittedAt: "2026-05-10T16:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_007",
    teamId: "team_navigators",
    title: "Keyboard shortcut to create new initiative",
    description: "Power users want to press 'C' anywhere in the app to open the new initiative modal.",
    businessContext: "Matches Linear UX — PMs familiar with this pattern",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "triaged",
    tags: ["keyboard", "ux", "shortcuts"],
    productArea: "Core Product",
    goalIds: [],
    submittedBy: "Zoe K.",
    submittedAt: "2026-05-12T13:00:00Z",
    votes: [
      { stakeholderId: "u_9", stakeholderName: "Alex Chen", comment: "100% agree", votedAt: "2026-05-13T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
];

// ── Hitchhiker Inbox Requests ──────────────

export const SEED_REQUESTS_HITCHHIKER: FeatureRequest[] = [
  {
    id: "hh_req_001",
    teamId: "team_hitchhiker",
    title: "Enable File Application Console for Operations Persona",
    description: "Enable File Application Console for Operations Persona",
    businessContext: "Improves operational efficiency for the operations persona",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["file-app", "console", "operations"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Ops Platform Team",
    submittedAt: "2026-05-02T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_002",
    teamId: "team_hitchhiker",
    title: "Customizable Side Navigation bar in Workbenches",
    description: "Allow administrators to customize workbench consoles and queue appearance in the left side nav: hide not required consoles/queues, rearrange console/queue order based on operational priority, hide the entire blue side navigation panel, and place additional consoles as required.",
    businessContext: "Reduces cognitive load for operations teams managing complex workbench setups",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["navigation", "workbench", "customization", "admin"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Operations Team",
    submittedAt: "2026-05-05T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_003",
    teamId: "team_hitchhiker",
    title: "Configurable Landing Page for Workbench",
    description: "Allow configuring the default landing console/queue for a workbench so users land on the most relevant view for their role.",
    businessContext: "Improves time-to-action for operations staff on workbench login",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "new",
    tags: ["workbench", "landing-page", "configuration"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "Ops Platform Team",
    submittedAt: "2026-05-06T11:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_004",
    teamId: "team_hitchhiker",
    title: "FE - Hub Inbox Console for Event App",
    description: "Enable user to seamlessly onboard and manage Inboxes and Inbox Clients through a unified frontend console for Hub Inbox (Event App processing mode), with clear visibility into request status, processing outcomes, and observability metrics, thereby improving operational efficiency.",
    businessContext: "Reduces manual intervention and improves observability for event-driven workflows",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["hub-inbox", "event-app", "frontend", "console"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-08T09:30:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_005",
    teamId: "team_hitchhiker",
    title: "File App - Audit Page Rework: Render Task Audit Without Mandatory Phase Attribute",
    description: "Rework the File App audit page to render task audit entries without requiring a mandatory Phase attribute, improving flexibility and reducing errors in audit display.",
    businessContext: "Unblocks audit workflows where Phase data is unavailable or not applicable",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["file-app", "audit", "ux"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-09T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_006",
    teamId: "team_hitchhiker",
    title: "File and schedule consoles implementation - SRE and BizOps",
    description: "Implement dedicated File and Schedule consoles within the SRE and BizOps workbenches to provide visibility into file processing and scheduling operations.",
    businessContext: "Gives SRE and BizOps teams direct visibility into file and schedule pipelines",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["file-console", "schedule", "sre", "bizops"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-10T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_007",
    teamId: "team_hitchhiker",
    title: "Business OC and SRE OC – File Application Console Run-First View",
    description: "Implement a Run-First view in the File Application Console for both Business OC and SRE OC workbenches, enabling operators to immediately see the most recent run status on load.",
    businessContext: "Reduces time to identify failed runs during incident response",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["file-app", "console", "run-first", "sre"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "BizOps Team",
    submittedAt: "2026-05-11T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_008",
    teamId: "team_hitchhiker",
    title: "SRE OC and Business OC – PCI File Applications Console Visibility & Support",
    description: "Add PCI File Application visibility and operational support to the SRE OC and Business OC consoles, enabling teams to monitor and manage PCI-scoped file applications.",
    businessContext: "Required for compliance teams to monitor PCI-classified file processing",
    source: "internal",
    prioritySignal: "critical",
    status: "new",
    tags: ["pci", "file-app", "compliance", "sre"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Compliance Team",
    submittedAt: "2026-05-11T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_009",
    teamId: "team_hitchhiker",
    title: "BE - Hub Inbox Console for Event App",
    description: "Enable user to seamlessly onboard and manage Inboxes and Inbox Clients through a unified backend service for Hub Inbox (Event App processing mode), with clear visibility into request status, processing outcomes, and observability metrics, thereby improving operational efficiency.",
    businessContext: "Backend counterpart to FE Hub Inbox Console — required for full feature delivery",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["hub-inbox", "event-app", "backend", "api"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-08T09:30:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_010",
    teamId: "team_hitchhiker",
    title: "Convert Bulk RD Processing to File Application Model in OP Center",
    description: "Bulk Request Definition (RD) processing in OP Center is currently not modeled as a file application, resulting in inconsistent user experiences, limited visibility, and heavy manual intervention. This proposes migrating all bulk RD workflows to the File Application framework, enabling progress tracking, exception generation, validation, and standardized UI/UX.",
    businessContext: "Eliminates inconsistent UX and reduces manual intervention in bulk RD workflows",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["bulk-rd", "file-app", "migration", "ux"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "Ops Platform Team",
    submittedAt: "2026-05-12T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_011",
    teamId: "team_hitchhiker",
    title: "SRE Operation Center V2 + Business Operation Center – Core Consoles Implementation [Phase 2]",
    description: "Phase 2 of SRE Operation Center V2 introduces Folder and Schedule Consoles within the SRE Workbench to enhance operational visibility and troubleshooting. It enables SREs to manage folders, track schedule lifecycles, and monitor run history.",
    businessContext: "Extends SRE visibility into folder and schedule pipelines, reducing MTTR",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["sre-oc", "phase-2", "folder-console", "schedule"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-13T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_012",
    teamId: "team_hitchhiker",
    title: "FE - Workbench Studio 0.2 – Self-Service Onboarding of Connectors/Commands",
    description: "Enable publishers to self-serve onboarding of new Connectors and Commands into Workbench Studio via a guided manual flow or OpenAPI spec upload.",
    businessContext: "Removes dependency on platform team for each connector onboarding — unblocks publishers",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["workbench-studio", "connectors", "self-service", "frontend"],
    productArea: "Workbench Studio",
    goalIds: [],
    submittedBy: "Studio Team",
    submittedAt: "2026-05-14T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_013",
    teamId: "team_hitchhiker",
    title: "BE - Workbench Studio 0.2 – Self-Service Onboarding of Connectors/Commands",
    description: "Enable publishers to self-serve onboarding of new Connectors and Commands into Workbench Studio via a guided manual flow or OpenAPI spec upload.",
    businessContext: "Backend services required for connector/command self-service onboarding",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["workbench-studio", "connectors", "self-service", "backend"],
    productArea: "Workbench Studio",
    goalIds: [],
    submittedBy: "Studio Team",
    submittedAt: "2026-05-14T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_014",
    teamId: "team_hitchhiker",
    title: "FE - Workbench Studio 0.3 – Self-Service Signal Onboarding (File, Events, Forms, Exceptions, Observations, Schedule, API)",
    description: "Enable Publishers to onboard new Signals of all supported types (File, Events, Request Forms, Exceptions, Observations, Schedule, API) into Workbench Studio via intuitive, guided flows. All onboarded Signals must be validated, versioned, and immediately available in the central Signal catalog for Automation Developers to discover and use.",
    businessContext: "Enables full self-service signal publishing without platform team bottleneck",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["workbench-studio", "signals", "self-service", "frontend"],
    productArea: "Workbench Studio",
    goalIds: [],
    submittedBy: "Studio Team",
    submittedAt: "2026-05-15T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_015",
    teamId: "team_hitchhiker",
    title: "BE - Workbench Studio 0.3 – Self-Service Signal Onboarding (File, Events, Forms, Exceptions, Observations, Schedule, API)",
    description: "Enable Publishers to onboard new Signals of all supported types (File, Events, Request Forms, Exceptions, Observations, Schedule, API) into Workbench Studio via intuitive, guided flows. All onboarded Signals must be validated, versioned, and immediately available in the central Signal catalog for Automation Developers to discover and use.",
    businessContext: "Backend infrastructure for signal onboarding, versioning, and catalog integration",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["workbench-studio", "signals", "self-service", "backend"],
    productArea: "Workbench Studio",
    goalIds: [],
    submittedBy: "Studio Team",
    submittedAt: "2026-05-15T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_016",
    teamId: "team_hitchhiker",
    title: "Notification mechanism for failed tasks in Operations Centre",
    description: "Currently, for any RD, once a task is approved by the reviewer, it moves to the Completed Tasks tab. However, the task outcome can be either successful or unsuccessful. The agent should receive a notification whenever a task is not executed successfully.",
    businessContext: "Prevents silent failures going unnoticed by agents managing task outcomes",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["notifications", "tasks", "operations-center", "alerts"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Operations Team",
    submittedAt: "2026-05-16T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_017",
    teamId: "team_hitchhiker",
    title: "Implement File Processing Progress & Status Using Perseus APIs",
    description: "As part of converting Bulk RD Processing to the File Application Model in OP Center, integrate Perseus APIs to surface real-time file processing progress and status to operators.",
    businessContext: "Provides real-time observability into file processing as part of the bulk RD migration",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["perseus", "file-processing", "progress", "api"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-17T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_018",
    teamId: "team_hitchhiker",
    title: "Self-serve display on Operations Center",
    description: "Self-serve display on Operations Center — allow teams to configure and customise their OP Center display without engineering involvement.",
    businessContext: "Reduces ops team dependency on engineering for routine display configuration",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "new",
    tags: ["self-serve", "operations-center", "configuration"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "BizOps Team",
    submittedAt: "2026-05-17T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_019",
    teamId: "team_hitchhiker",
    title: "Deprecate IO storage in favor of DiaStorage",
    description: "Migrate all IO storage references to DiaStorage, deprecating the legacy IO storage layer to reduce maintenance overhead and align with the platform storage standard.",
    businessContext: "Reduces dual-storage maintenance burden and aligns platform on a single storage layer",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["storage", "migration", "tech-debt", "diastorage"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-18T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_020",
    teamId: "team_hitchhiker",
    title: "TraceId tracking in Ops Platform services",
    description: "TraceId tracking in Ops Platform services — propagate TraceId across all Ops Platform service boundaries to enable end-to-end distributed tracing.",
    businessContext: "Enables full distributed tracing across services, reducing MTTR for cross-service incidents",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["observability", "tracing", "trace-id", "platform"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-18T11:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_021",
    teamId: "team_hitchhiker",
    title: "Remove workbench.deletion.enabled feature flag",
    description: "Remove the workbench.deletion.enabled feature flag now that workbench deletion is fully rolled out, cleaning up flag infrastructure and conditional code paths.",
    businessContext: "Removes dead code and flag infrastructure after full rollout",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "new",
    tags: ["feature-flag", "cleanup", "tech-debt"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-19T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_022",
    teamId: "team_hitchhiker",
    title: "Operations Management: Support for additional filters",
    description: "The Request Listing API currently does not support filtering records based on the creator of the request. This feature introduces support for a createdBy filter in the API, enabling consumers to retrieve records created by specific users.",
    businessContext: "Enables audit and attribution queries on request listings without workarounds",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["api", "filters", "request-listing", "ops-management"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "Ops Platform Team",
    submittedAt: "2026-05-19T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_023",
    teamId: "team_hitchhiker",
    title: "Operations Center: Expose History tab of RD Details page",
    description: "Improve the usability, flexibility, and clarity of the history/activity module by making the History component reusable, enhancing UI elements, improving activity messaging, and supporting visibility of failed and successful records for bulk operations.",
    businessContext: "Makes RD audit history accessible directly in OP Center without leaving context",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["history", "rd-details", "operations-center", "ux"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Operations Team",
    submittedAt: "2026-05-20T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_024",
    teamId: "team_hitchhiker",
    title: "Ops Platform: Resiliency and Observability Across All Backend Services",
    description: "Improve resiliency (circuit breakers, retries, timeouts) and observability (metrics, alerts, dashboards) across all Ops Platform backend services to meet reliability SLOs.",
    businessContext: "Required to meet 99.9% uptime SLO across all Ops Platform services",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["resiliency", "observability", "slo", "platform"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-20T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_025",
    teamId: "team_hitchhiker",
    title: "Rhea - Unauthenticated API Endpoints Identified from Cloudflare WAF Logs - Review & Action Required",
    description: "Cloudflare WAF logs have identified unauthenticated API endpoints in Rhea. A full review and remediation of all unauthenticated endpoints is required to prevent unauthorised access.",
    businessContext: "Critical security exposure — unauthenticated endpoints must be remediated immediately",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["security", "rhea", "api", "waf", "authentication"],
    productArea: "Rhea",
    goalIds: [],
    submittedBy: "Security Team",
    submittedAt: "2026-05-21T08:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_026",
    teamId: "team_hitchhiker",
    title: "CCE Adoption for Olympus Hub Modules: Operations Management, Rhea and Operation Center App",
    description: "Adopt Cloud Control Engine (CCE) patterns across Olympus Hub modules — Operations Management, Rhea, and Operation Center App — to align with platform-wide deployment and configuration standards.",
    businessContext: "Aligns hub modules with platform CCE standard, enabling consistent deployment and scaling",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["cce", "olympus-hub", "platform", "adoption"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-21T10:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_027",
    teamId: "team_hitchhiker",
    title: "JSD as Task BE for OPS Center Tasks (POC)",
    description: "Proof of concept to evaluate Jira Service Desk (JSD) as the backend task engine for OPS Center task management, replacing or supplementing the current task backend.",
    businessContext: "Explores whether JSD can reduce custom task infrastructure maintenance in OPS Center",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "new",
    tags: ["jsd", "jira", "poc", "tasks", "ops-center"],
    productArea: "Operations Platform",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-22T09:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_028",
    teamId: "team_hitchhiker",
    title: "Ops Center UI + BE: Replace reference of Workbench ID to Workbench Code",
    description: "Replace all references to Workbench ID with Workbench Code across both the Ops Center UI and backend services to align with the canonical identifier used across the platform.",
    businessContext: "Prevents ID/Code mismatch errors and aligns Ops Center with platform-wide Workbench Code standard",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["workbench", "identifier", "refactor", "ops-center"],
    productArea: "Operations Center",
    goalIds: [],
    submittedBy: "Platform Engineering",
    submittedAt: "2026-05-22T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
];

// ── Quarterly Goals ────────────────────────

const SEED_GOALS: QuarterlyGoal[] = [
  {
    id: "goal_001",
    title: "Deliver MVP scoring engine",
    description: "Launch RICE, MoSCoW, WSJF scoring in a single view",
    owningTeam: "Product",
    kpiTarget: "WAU > 60% of registered PMs",
    weight: 5,
    quarter: Q2_2026,
    color: "#5e5ce6",
  },
  {
    id: "goal_002",
    title: "Stakeholder-ready roadmap output",
    description: "Shareable, polished roadmap view replacing slide decks",
    owningTeam: "Product",
    kpiTarget: "NPS > 50 at 3 months",
    weight: 4,
    quarter: Q2_2026,
    color: "#30a46c",
  },
  {
    id: "goal_003",
    title: "Jira & Linear integrations",
    description: "One-click push of approved initiatives to execution tools",
    owningTeam: "Engineering",
    kpiTarget: "40% of plans use integration",
    weight: 3,
    quarter: Q2_2026,
    color: "#f5a623",
  },
];

// ── Roadmap Initiatives ────────────────────

export const SEED_INITIATIVES: RoadmapItem[] = [
  {
    id: "init_001",
    featureRequestId: "req_001",
    title: "Bulk triage actions",
    description: "Multi-select + bulk status/tag operations in inbox",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_001"],
    productArea: "Core Product",
    status: "in_progress",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_001",
      framework: "rice",
      rice: { reach: 500, impact: 2, confidence: 80, effort: 2, score: 400 },
      moscow: "must",
      wsjf: null,
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-20T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_002",
    featureRequestId: "req_002",
    title: "WSJF scoring framework",
    description: "Full WSJF scoring with cost-of-delay and job-size inputs",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_001"],
    productArea: "Core Product",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_002",
      framework: "rice",
      rice: { reach: 300, impact: 2, confidence: 90, effort: 3, score: 180 },
      moscow: "must",
      wsjf: null,
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-19T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [{ initiativeId: "init_001", type: "blocked_by" }],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-18T11:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_003",
    featureRequestId: "req_003",
    title: "Shareable read-only roadmap",
    description: "Public link generation, password protection, live-updating view",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_002"],
    productArea: "Roadmap Planning",
    status: "todo",
    priority: "urgent",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_003",
      framework: "rice",
      rice: { reach: 1000, impact: 3, confidence: 85, effort: 2, score: 1275 },
      moscow: "must",
      wsjf: null,
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-15T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T08:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_004",
    featureRequestId: "req_004",
    title: "Linear integration",
    description: "OAuth + one-click push of initiatives to Linear projects",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_003"],
    productArea: "Integrations",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_004",
      framework: "rice",
      rice: { reach: 400, impact: 2, confidence: 70, effort: 5, score: 112 },
      moscow: "should",
      wsjf: null,
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-22T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-22T14:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_005",
    featureRequestId: "req_005",
    title: "Capacity planning bar",
    description: "Real-time capacity meter in roadmap view; over-capacity warnings",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_002"],
    productArea: "Roadmap Planning",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_005",
      framework: "rice",
      rice: { reach: 800, impact: 2, confidence: 90, effort: 1, score: 1440 },
      moscow: "must",
      wsjf: null,
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-23T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-23T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

// ── Quarterly Plan ─────────────────────────

export const SEED_PLAN: QuarterlyPlan = {
  id: "plan_q2_2026",
  quarter: Q2_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: SEED_GOALS,
  items: SEED_INITIATIVES,
  capacity: {
    unit: "story_points",
    total: 60,
    committed: SEED_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0),
    warningThreshold: 0.9,
    byArea: {},
  },
  reviewers: [
    {
      userId: "u_eng_lead",
      name: "Jordan S.",
      email: "jordan@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
    {
      userId: "u_vp",
      name: "Morgan L.",
      email: "morgan@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
  ],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-01T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Hitchhiker team plan ───────────────────

const HITCHHIKER_GOALS: QuarterlyGoal[] = [
  {
    id: "hh_goal_001",
    title: "Platform reliability",
    description: "Achieve 99.9% uptime and reduce P1 incidents by 50%",
    owningTeam: "Hitchhiker",
    kpiTarget: "P1 incidents < 2 per quarter",
    weight: 5,
    quarter: Q2_2026,
    color: "#30a46c",
  },
  {
    id: "hh_goal_002",
    title: "Developer experience",
    description: "Reduce onboarding time for new engineers from 2 weeks to 3 days",
    owningTeam: "Hitchhiker",
    kpiTarget: "Onboarding time ≤ 3 days",
    weight: 4,
    quarter: Q2_2026,
    color: "#3b82f6",
  },
  {
    id: "hh_goal_003",
    title: "API performance",
    description: "Bring p95 API latency under 200ms across all endpoints",
    owningTeam: "Hitchhiker",
    kpiTarget: "p95 latency < 200ms",
    weight: 3,
    quarter: Q2_2026,
    color: "#f97316",
  },
];

const HITCHHIKER_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_init_001",
    featureRequestId: null,
    title: "Database query optimisation",
    description: "Add missing indexes, rewrite N+1 queries, enable query plan caching",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_003"],
    productArea: "Platform",
    status: "in_progress",
    priority: "urgent",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_001",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 8, jobSize: 2, score: 4 },
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-19T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_002",
    featureRequestId: null,
    title: "Automated incident runbooks",
    description: "Codify P1/P2 runbooks, wire into PagerDuty alerts",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001"],
    productArea: "Platform",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_002",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 9, jobSize: 3, score: 3 },
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-20T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-12T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_003",
    featureRequestId: null,
    title: "Internal dev tooling portal",
    description: "Unified portal for env setup, docs, and CI status per service",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_002"],
    productArea: "Developer Experience",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_003",
      framework: "wsjf",
      rice: null,
      moscow: "should",
      wsjf: { costOfDelay: 6, jobSize: 5, score: 1.2 },
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-21T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-14T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_004",
    featureRequestId: null,
    title: "Service mesh migration",
    description: "Migrate inter-service calls to Istio for mTLS and traffic observability",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001", "hh_goal_003"],
    productArea: "Infrastructure",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_004",
      framework: "wsjf",
      rice: null,
      moscow: "could",
      wsjf: { costOfDelay: 5, jobSize: 8, score: 0.625 },
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-22T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [{ initiativeId: "hh_init_001", type: "blocked_by" }],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-16T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_005",
    featureRequestId: null,
    title: "On-call rotation tooling",
    description: "Automate handoff notes, schedule rotations, track fatigue metrics",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001"],
    productArea: "Developer Experience",
    status: "done",
    priority: "high",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_005",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 7, jobSize: 1, score: 7 },
      custom: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-17T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

const HITCHHIKER_COMMITTED = HITCHHIKER_INITIATIVES.reduce(
  (s, i) => s + (i.effort.points ?? 0),
  0,
);

export const SEED_PLAN_HITCHHIKER: QuarterlyPlan = {
  id: "plan_hh_q2_2026",
  quarter: Q2_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "in_review",
  goals: HITCHHIKER_GOALS,
  items: HITCHHIKER_INITIATIVES,
  capacity: {
    unit: "story_points",
    total: 80,
    committed: HITCHHIKER_COMMITTED,
    warningThreshold: 0.9,
    byArea: {},
  },
  reviewers: [
    {
      userId: "u_cto",
      name: "Sam Rivera",
      email: "sam@keel.so",
      required: true,
      decision: "approved",
      comment: "Looks solid. Ship it.",
      reviewedAt: "2026-05-22T14:00:00Z",
    },
    {
      userId: "u_vp_eng",
      name: "Dana Kim",
      email: "dana@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
  ],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-02T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};
