import type {
  FeatureRequest,
  RoadmapItem,
  QuarterlyPlan,
  QuarterlyGoal,
} from "@/types";
import { makeQuarterRef } from "./constants";

const Q2_2026 = makeQuarterRef(2026, 2);
const Q3_2026 = makeQuarterRef(2026, 3);
const Q4_2026 = makeQuarterRef(2026, 4);

// ── Feature Requests (Inbox) ───────────────

export const SEED_REQUESTS: FeatureRequest[] = [
  {
    id: "req_001",
    teamId: "team_navigators",
    title: "Bulk status update for feature requests",
    description: "PMs need to triage 50+ items at once. Currently requires clicking each row individually.",
    businessContext: "Saves ~2 hours per planning cycle",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["triage", "bulk-actions", "inbox"],
    productArea: "Core Product",
    goalIds: ["goal_001"],
    submittedBy: "Sarah K.",
    submittedAt: "2026-05-20T09:00:00Z",
    votes: [
      { stakeholderId: "u_2", stakeholderName: "Marcus T.", comment: "Critical for our workflow", votedAt: "2026-05-21T10:00:00Z" },
      { stakeholderId: "u_3", stakeholderName: "Priya N.", comment: null, votedAt: "2026-05-21T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_002",
    teamId: "team_navigators",
    title: "WSJF scoring framework support",
    description: "Our team uses Weighted Shortest Job First for hardware-adjacent roadmap items. RICE doesn't map well.",
    businessContext: "Unblocks 3 PMs who currently maintain separate spreadsheets",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["scoring", "frameworks", "wsjf"],
    productArea: "Core Product",
    goalIds: ["goal_001"],
    submittedBy: "James R.",
    submittedAt: "2026-05-18T11:30:00Z",
    votes: [
      { stakeholderId: "u_4", stakeholderName: "Anita L.", comment: "Already on the roadmap?", votedAt: "2026-05-19T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_003",
    teamId: "team_navigators",
    title: "Shareable read-only roadmap view",
    description: "Need to send a polished roadmap link to leadership without giving them edit access.",
    businessContext: "Eliminates the quarterly slide deck rebuild",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["roadmap", "sharing", "stakeholders"],
    productArea: "Roadmap Planning",
    goalIds: ["goal_002"],
    submittedBy: "VP Product",
    submittedAt: "2026-05-15T08:00:00Z",
    votes: [
      { stakeholderId: "u_5", stakeholderName: "Tomás V.", comment: "Would save our leadership prep", votedAt: "2026-05-16T10:00:00Z" },
      { stakeholderId: "u_6", stakeholderName: "Hana M.", comment: "Yes please", votedAt: "2026-05-16T11:00:00Z" },
      { stakeholderId: "u_7", stakeholderName: "David P.", comment: null, votedAt: "2026-05-17T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_004",
    teamId: "team_navigators",
    title: "Linear integration — push initiatives as projects",
    description: "After approving the plan, we manually recreate everything in Linear. One-click push would save hours.",
    businessContext: "~4 hours saved per planning cycle per PM",
    source: "internal",
    prioritySignal: "critical",
    status: "new",
    tags: ["integrations", "linear", "automation"],
    productArea: "Integrations",
    goalIds: ["goal_003"],
    submittedBy: "Eng Lead",
    submittedAt: "2026-05-22T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_005",
    teamId: "team_navigators",
    title: "Capacity bar in roadmap view",
    description: "We keep over-committing. A visual capacity meter that updates as items are added would prevent this.",
    businessContext: "Prevents over-commitment before plan is locked",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["roadmap", "capacity", "planning"],
    productArea: "Roadmap Planning",
    goalIds: ["goal_002"],
    submittedBy: "Alex Chen",
    submittedAt: "2026-05-23T09:00:00Z",
    votes: [
      { stakeholderId: "u_8", stakeholderName: "Lena B.", comment: "Essential", votedAt: "2026-05-23T10:30:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_006",
    teamId: "team_navigators",
    title: "Email digest for voting round outcomes",
    description: "PMs should receive a summary when a voting round closes, not have to manually check.",
    businessContext: "Reduces time lost to manual follow-up",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "archived",
    tags: ["notifications", "email", "voting"],
    productArea: "Notifications",
    goalIds: [],
    submittedBy: "Priya N.",
    submittedAt: "2026-05-10T16:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_007",
    teamId: "team_navigators",
    title: "Keyboard shortcut to create new initiative",
    description: "Power users want to press 'C' anywhere in the app to open the new initiative modal.",
    businessContext: "Matches Linear UX — PMs familiar with this pattern",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "triaged",
    tags: ["keyboard", "ux", "shortcuts"],
    productArea: "Core Product",
    goalIds: [],
    submittedBy: "Zoe K.",
    submittedAt: "2026-05-12T13:00:00Z",
    votes: [
      { stakeholderId: "u_9", stakeholderName: "Alex Chen", comment: "100% agree", votedAt: "2026-05-13T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
];

// ── Hitchhiker Inbox Requests ──────────────

export const SEED_REQUESTS_HITCHHIKER: FeatureRequest[] = [
  {
    id: "hh_req_001",
    teamId: "team_hitchhiker",
    title: "Public system status page with real-time incident updates",
    description: "When we have an outage, customers flood support with tickets before we can communicate anything. A live status page with incident timelines would let customers self-serve and reduce support load during incidents.",
    businessContext: "Support ticket volume spikes 5x during outages. Last quarter's P1 cost ~$40K in support hours.",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["reliability", "communication", "incidents", "transparency"],
    productArea: "Platform",
    goalIds: ["hh_goal_001"],
    submittedBy: "VP Customer Success",
    submittedAt: "2026-05-03T09:00:00Z",
    votes: [
      { stakeholderId: "u_hh_1", stakeholderName: "Ravi M.", comment: "Every customer asks us for this during incidents", votedAt: "2026-05-04T10:00:00Z" },
      { stakeholderId: "u_hh_2", stakeholderName: "Selin A.", comment: "Agreed — we look unprofessional without one", votedAt: "2026-05-04T14:00:00Z" },
      { stakeholderId: "u_hh_3", stakeholderName: "Tom B.", comment: null, votedAt: "2026-05-05T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_002",
    teamId: "team_hitchhiker",
    title: "API rate limit visibility and self-service quota management",
    description: "Customers hitting rate limits get a generic 429 with no context on their current usage, reset times, or how to request higher limits. We need a dashboard where they can monitor consumption and request quota increases.",
    businessContext: "Rate limit complaints are our #3 support category. Several enterprise customers threatened churn in Q1.",
    source: "customer",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["api", "rate-limiting", "developer-experience", "self-service"],
    productArea: "Platform",
    goalIds: ["hh_goal_002"],
    submittedBy: "Priya N. (Acme Corp)",
    submittedAt: "2026-05-06T11:30:00Z",
    votes: [
      { stakeholderId: "u_hh_4", stakeholderName: "James R.", comment: "We hit this weekly — our integration team is frustrated", votedAt: "2026-05-07T09:00:00Z" },
      { stakeholderId: "u_hh_5", stakeholderName: "Yuki T.", comment: "Would unlock our high-frequency use case", votedAt: "2026-05-07T11:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_003",
    teamId: "team_hitchhiker",
    title: "Self-service environment provisioning for engineers",
    description: "Engineers currently wait 2–4 days for DevOps to provision a new staging environment. We need a self-service portal where engineers can spin up isolated environments from a template in under 10 minutes.",
    businessContext: "New engineers lose ~3 days in their first week waiting on environment setup. Cross-team dependencies add more delays.",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["developer-experience", "environments", "self-service", "onboarding"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_002"],
    submittedBy: "Eng Lead",
    submittedAt: "2026-05-08T10:00:00Z",
    votes: [
      { stakeholderId: "u_hh_6", stakeholderName: "Dana K.", comment: "This is the #1 complaint in our retrospectives", votedAt: "2026-05-09T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_004",
    teamId: "team_hitchhiker",
    title: "Webhook retry logic and dead-letter queue",
    description: "When our API delivers webhook events and the customer endpoint is temporarily unavailable, the event is dropped silently. We need configurable retry logic with exponential back-off and a dead-letter queue customers can replay from.",
    businessContext: "We've lost customer trust after silent webhook failures caused data inconsistencies in downstream systems.",
    source: "customer",
    prioritySignal: "critical",
    status: "new",
    tags: ["webhooks", "reliability", "api", "events"],
    productArea: "Platform",
    goalIds: ["hh_goal_001"],
    submittedBy: "Mateo L. (BuildFast)",
    submittedAt: "2026-05-10T14:00:00Z",
    votes: [
      { stakeholderId: "u_hh_7", stakeholderName: "Anita B.", comment: "This caused a P2 for us last month", votedAt: "2026-05-11T10:00:00Z" },
      { stakeholderId: "u_hh_8", stakeholderName: "Chen W.", comment: "Our data sync relies on reliable webhooks", votedAt: "2026-05-11T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_005",
    teamId: "team_hitchhiker",
    title: "API deprecation notices and advance warning emails",
    description: "The last time we deprecated an endpoint, customers only found out when their integrations broke in production. We need a formal deprecation process: in-response headers, dashboard warnings, and 90-day email notices before any endpoint is removed.",
    businessContext: "Two enterprise customers escalated to exec level after silent API deprecations broke their production integrations.",
    source: "customer",
    prioritySignal: "important",
    status: "triaged",
    tags: ["api", "deprecation", "developer-experience", "communication"],
    productArea: "Platform",
    goalIds: ["hh_goal_002"],
    submittedBy: "Lena B. (Dataflow)",
    submittedAt: "2026-05-11T09:00:00Z",
    votes: [
      { stakeholderId: "u_hh_9", stakeholderName: "Sam R.", comment: "Industry standard practice — we should have had this from day one", votedAt: "2026-05-12T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_006",
    teamId: "team_hitchhiker",
    title: "Automated dependency vulnerability scanning in CI",
    description: "Our current security review process is manual and quarterly. We need automated scanning for vulnerable dependencies in every pull request, with severity gates that block merges on critical CVEs.",
    businessContext: "Security audit flagged 14 unpatched CVEs in Q1. Manual review misses newly disclosed vulnerabilities between cycles.",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["security", "ci", "dependencies", "vulnerability-scanning"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_001"],
    submittedBy: "Security Lead",
    submittedAt: "2026-05-12T08:00:00Z",
    votes: [
      { stakeholderId: "u_hh_10", stakeholderName: "Jordan S.", comment: "Should be mandatory — we're headed to SOC 2 and this is a requirement", votedAt: "2026-05-13T10:00:00Z" },
      { stakeholderId: "u_hh_11", stakeholderName: "Morgan L.", comment: null, votedAt: "2026-05-13T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_007",
    teamId: "team_hitchhiker",
    title: "API usage analytics dashboard for developers",
    description: "Customers building on our platform have no visibility into which endpoints they call most, error rates by endpoint, or latency trends over time. A usage dashboard would help them optimise their integrations and debug issues faster.",
    businessContext: "Reduces support tickets from developers investigating their own integration health. Competitors (Stripe, Twilio) all offer this.",
    source: "customer",
    prioritySignal: "important",
    status: "new",
    tags: ["api", "analytics", "developer-experience", "observability"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_002", "hh_goal_003"],
    submittedBy: "Product Marketing",
    submittedAt: "2026-05-13T11:00:00Z",
    votes: [
      { stakeholderId: "u_hh_12", stakeholderName: "Zoe K.", comment: "I've had three sales calls this month where this was asked about", votedAt: "2026-05-14T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_008",
    teamId: "team_hitchhiker",
    title: "p95 latency SLO alerts and dashboard for platform teams",
    description: "We don't have any automated alerting when our p95 latency degrades — we only notice when customers complain. We need dashboards showing latency by endpoint over time, with PagerDuty alerts when p95 exceeds our 200ms SLO.",
    businessContext: "Latency regressions currently go undetected for days. MTTR is high because we're always reactive, never proactive.",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["observability", "latency", "slo", "alerting"],
    productArea: "Platform",
    goalIds: ["hh_goal_001", "hh_goal_003"],
    submittedBy: "SRE Lead",
    submittedAt: "2026-05-15T09:00:00Z",
    votes: [
      { stakeholderId: "u_hh_13", stakeholderName: "Ravi M.", comment: "This is foundational — hard to justify the Q3 reliability goal without it", votedAt: "2026-05-15T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_009",
    teamId: "team_hitchhiker",
    title: "Interactive API reference with live code examples",
    description: "Our current API docs are static Markdown. Developers have to copy snippets into Postman to try anything. We need interactive docs (like Stripe's) where they can authenticate and execute real API calls from the browser.",
    businessContext: "Time-to-first-API-call is currently 3–4 hours. Interactive docs could cut that to under 30 minutes, improving conversion from trial to paid.",
    source: "customer",
    prioritySignal: "important",
    status: "new",
    tags: ["documentation", "developer-experience", "api", "onboarding"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_002"],
    submittedBy: "Growth Team",
    submittedAt: "2026-05-17T10:00:00Z",
    votes: [
      { stakeholderId: "u_hh_14", stakeholderName: "Alex C.", comment: "Our trial-to-paid conversion is below benchmark — docs friction is one culprit", votedAt: "2026-05-18T09:00:00Z" },
      { stakeholderId: "u_hh_15", stakeholderName: "Priya N.", comment: "Would have saved me hours of debugging on day one", votedAt: "2026-05-18T11:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_010",
    teamId: "team_hitchhiker",
    title: "Canary deployment support for API rollouts",
    description: "We currently do big-bang deployments and roll back manually when something breaks. We need a canary deployment pipeline that routes a small percentage of traffic to a new release before full rollout, with automatic rollback on error-rate thresholds.",
    businessContext: "Two of our last three P1 incidents were caused by full-traffic deployments of regressions that canary traffic would have caught.",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["reliability", "deployment", "canary", "platform"],
    productArea: "Platform",
    goalIds: ["hh_goal_001"],
    submittedBy: "Platform Lead",
    submittedAt: "2026-05-19T14:00:00Z",
    votes: [
      { stakeholderId: "u_hh_16", stakeholderName: "Dana K.", comment: "Would have prevented the March incident", votedAt: "2026-05-20T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_011",
    teamId: "team_hitchhiker",
    title: "Infrastructure cost attribution by team and service",
    description: "Our cloud bill is growing 40% quarter-over-quarter but we have no visibility into which team or service is driving costs. We need per-service cost dashboards with weekly team-level summaries so engineering leads can make informed build-vs-optimise decisions.",
    businessContext: "Q1 cloud spend was 18% over budget. Finance is asking engineering to present a cost-reduction plan but we have no data to back decisions.",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "new",
    tags: ["cost", "platform", "observability", "finance"],
    productArea: "Platform",
    goalIds: [],
    submittedBy: "CFO",
    submittedAt: "2026-05-21T10:00:00Z",
    votes: [
      { stakeholderId: "u_hh_17", stakeholderName: "Morgan L.", comment: "Finance flagged this as urgent — worth prioritising", votedAt: "2026-05-21T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_012",
    teamId: "team_hitchhiker",
    title: "Automated on-call handoff notes from incident history",
    description: "On-call engineers currently write handoff notes manually at the end of each shift. The information already exists in our incident tracking — we should auto-generate a structured summary of open incidents, recent changes, and known risks for the incoming on-call.",
    businessContext: "Incomplete handoffs have contributed to two incidents where the incoming on-call lacked context. Manual notes take ~45 minutes per handoff.",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "archived",
    tags: ["on-call", "developer-experience", "automation", "reliability"],
    productArea: "Developer Experience",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-10T16:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
];

// ── Quarterly Goals ────────────────────────

const SEED_GOALS: QuarterlyGoal[] = [
  {
    id: "goal_001",
    title: "Deliver MVP scoring engine",
    description: "Launch RICE, MoSCoW, WSJF scoring in a single view",
    owningTeam: "Product",
    kpiTarget: "WAU > 60% of registered PMs",
    weight: 5,
    quarter: Q2_2026,
    color: "#5e5ce6",
  },
  {
    id: "goal_002",
    title: "Stakeholder-ready roadmap output",
    description: "Shareable, polished roadmap view replacing slide decks",
    owningTeam: "Product",
    kpiTarget: "NPS > 50 at 3 months",
    weight: 4,
    quarter: Q2_2026,
    color: "#30a46c",
  },
  {
    id: "goal_003",
    title: "Jira & Linear integrations",
    description: "One-click push of approved initiatives to execution tools",
    owningTeam: "Engineering",
    kpiTarget: "40% of plans use integration",
    weight: 3,
    quarter: Q2_2026,
    color: "#f5a623",
  },
];

// ── Roadmap Initiatives ────────────────────

export const SEED_INITIATIVES: RoadmapItem[] = [
  {
    id: "init_001",
    teamId: "team_navigators",
    featureRequestId: "req_001",
    title: "Bulk triage actions",
    description: "Multi-select + bulk status/tag operations in inbox",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_001"],
    productArea: "Core Product",
    status: "in_progress",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_001",
      framework: "rice",
      rice: { reach: 500, impact: 2, confidence: 80, effort: 2, score: 400 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-20T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_002",
    teamId: "team_navigators",
    featureRequestId: "req_002",
    title: "WSJF scoring framework",
    description: "Full WSJF scoring with cost-of-delay and job-size inputs",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_001"],
    productArea: "Core Product",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_002",
      framework: "rice",
      rice: { reach: 300, impact: 2, confidence: 90, effort: 3, score: 180 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-19T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [{ initiativeId: "init_001", type: "blocked_by" }],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-18T11:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_003",
    teamId: "team_navigators",
    featureRequestId: "req_003",
    title: "Shareable read-only roadmap",
    description: "Public link generation, password protection, live-updating view",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_002"],
    productArea: "Roadmap Planning",
    status: "todo",
    priority: "urgent",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_003",
      framework: "rice",
      rice: { reach: 1000, impact: 3, confidence: 85, effort: 2, score: 1275 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-15T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T08:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_004",
    teamId: "team_navigators",
    featureRequestId: "req_004",
    title: "Linear integration",
    description: "OAuth + one-click push of initiatives to Linear projects",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_003"],
    productArea: "Integrations",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_004",
      framework: "rice",
      rice: { reach: 400, impact: 2, confidence: 70, effort: 5, score: 112 },
      moscow: "should",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-22T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-22T14:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_005",
    teamId: "team_navigators",
    featureRequestId: "req_005",
    title: "Capacity planning bar",
    description: "Real-time capacity meter in roadmap view; over-capacity warnings",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_002"],
    productArea: "Roadmap Planning",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_005",
      framework: "rice",
      rice: { reach: 800, impact: 2, confidence: 90, effort: 1, score: 1440 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-23T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-23T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

// ── Quarterly Plan ─────────────────────────

export const SEED_PLAN: QuarterlyPlan = {
  id: "plan_q2_2026",
  quarter: Q2_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: SEED_GOALS,
  items: SEED_INITIATIVES,
  capacity: {
    unit: "story_points",
    total: 60,
    committed: SEED_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0),
    warningThreshold: 0.9,
    byArea: {},
  },
  reviewers: [
    {
      userId: "u_eng_lead",
      name: "Jordan S.",
      email: "jordan@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
    {
      userId: "u_vp",
      name: "Morgan L.",
      email: "morgan@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
  ],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-01T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Hitchhiker team plan ───────────────────

const HITCHHIKER_GOALS: QuarterlyGoal[] = [
  {
    id: "hh_goal_001",
    title: "Platform reliability",
    description: "Achieve 99.9% uptime and reduce P1 incidents by 50%",
    owningTeam: "Hitchhikers Team",
    kpiTarget: "P1 incidents < 2 per quarter",
    weight: 5,
    quarter: Q2_2026,
    color: "#30a46c",
  },
  {
    id: "hh_goal_002",
    title: "Developer experience",
    description: "Reduce onboarding time for new engineers from 2 weeks to 3 days",
    owningTeam: "Hitchhikers Team",
    kpiTarget: "Onboarding time ≤ 3 days",
    weight: 4,
    quarter: Q2_2026,
    color: "#3b82f6",
  },
  {
    id: "hh_goal_003",
    title: "API performance",
    description: "Bring p95 API latency under 200ms across all endpoints",
    owningTeam: "Hitchhikers Team",
    kpiTarget: "p95 latency < 200ms",
    weight: 3,
    quarter: Q2_2026,
    color: "#f97316",
  },
];

const HITCHHIKER_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_init_001",
    featureRequestId: null,
    title: "Database query optimisation",
    description: "Add missing indexes, rewrite N+1 queries, enable query plan caching",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_003"],
    productArea: "Platform",
    status: "in_progress",
    priority: "urgent",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_001",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 8, jobSize: 2, score: 4 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-19T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_002",
    featureRequestId: null,
    title: "Automated incident runbooks",
    description: "Codify P1/P2 runbooks, wire into PagerDuty alerts",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001"],
    productArea: "Platform",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_002",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 9, jobSize: 3, score: 3 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-20T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-12T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_003",
    featureRequestId: null,
    title: "Internal dev tooling portal",
    description: "Unified portal for env setup, docs, and CI status per service",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_002"],
    productArea: "Developer Experience",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_003",
      framework: "wsjf",
      rice: null,
      moscow: "should",
      wsjf: { costOfDelay: 6, jobSize: 5, score: 1.2 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-21T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-14T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_004",
    featureRequestId: null,
    title: "Service mesh migration",
    description: "Migrate inter-service calls to Istio for mTLS and traffic observability",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001", "hh_goal_003"],
    productArea: "Infrastructure",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_004",
      framework: "wsjf",
      rice: null,
      moscow: "could",
      wsjf: { costOfDelay: 5, jobSize: 8, score: 0.625 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-22T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [{ initiativeId: "hh_init_001", type: "blocked_by" }],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-16T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_005",
    featureRequestId: null,
    title: "On-call rotation tooling",
    description: "Automate handoff notes, schedule rotations, track fatigue metrics",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001"],
    productArea: "Developer Experience",
    status: "done",
    priority: "high",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_005",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 7, jobSize: 1, score: 7 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-17T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

const HITCHHIKER_COMMITTED = HITCHHIKER_INITIATIVES.reduce(
  (s, i) => s + (i.effort.points ?? 0),
  0,
);

export const SEED_PLAN_HITCHHIKER: QuarterlyPlan = {
  id: "plan_hh_q2_2026",
  quarter: Q2_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "in_review",
  goals: HITCHHIKER_GOALS,
  items: HITCHHIKER_INITIATIVES,
  capacity: {
    unit: "story_points",
    total: 80,
    committed: HITCHHIKER_COMMITTED,
    warningThreshold: 0.9,
    byArea: {},
  },
  reviewers: [
    {
      userId: "u_cto",
      name: "Sam Rivera",
      email: "sam@keel.so",
      required: true,
      decision: "approved",
      comment: "Looks solid. Ship it.",
      reviewedAt: "2026-05-22T14:00:00Z",
    },
    {
      userId: "u_vp_eng",
      name: "Dana Kim",
      email: "dana@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
  ],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-02T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q3 2026 — Navigators ────────────────────

const NAV_Q3_GOALS: QuarterlyGoal[] = [
  { id: "nav_q3_g1", title: "AI-powered triage", description: "Surface highest-signal requests automatically", owningTeam: "Navigators Team", kpiTarget: "80% auto-triaged within 24h", weight: 5, quarter: Q3_2026, color: "#5e5ce6" },
  { id: "nav_q3_g2", title: "Mobile expansion",  description: "Native mobile experience for on-the-go triage", owningTeam: "Navigators Team", kpiTarget: "iOS & Android beta shipped", weight: 4, quarter: Q3_2026, color: "#ec4899" },
  { id: "nav_q3_g3", title: "API v2 public launch", description: "Open platform to third-party integrations", owningTeam: "Navigators Team", kpiTarget: "10 external integrations live", weight: 3, quarter: Q3_2026, color: "#30a46c" },
];

const NAV_Q3_INITIATIVES: RoadmapItem[] = [
  {
    id: "nav_q3_i1",
    featureRequestId: null,
    title: "AI triage assistant",
    description: "ML model that scores incoming requests by impact and novelty",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g1"],
    productArea: "Core Product",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i1", framework: "rice", rice: { reach: 500, impact: 4, confidence: 70, effort: 8, score: 175 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q3_i2",
    featureRequestId: null,
    title: "iOS app — triage & review",
    description: "Native iOS app for triaging requests and reviewing plans on mobile",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g2"],
    productArea: "Growth",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i2", framework: "rice", rice: { reach: 800, impact: 3, confidence: 60, effort: 13, score: 111 }, moscow: "should", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q3_i3",
    featureRequestId: null,
    title: "Public API v2 — stable endpoints",
    description: "Versioned REST API with OpenAPI spec and JS/Python SDKs",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g3"],
    productArea: "Integrations",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i3", framework: "rice", rice: { reach: 300, impact: 4, confidence: 80, effort: 5, score: 192 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q3_i4",
    featureRequestId: null,
    title: "Bulk export (CSV / JSON)",
    description: "Export the full request backlog and roadmap items for reporting",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g3"],
    productArea: "Core Product",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i4", framework: "rice", rice: { reach: 400, impact: 2, confidence: 90, effort: 2, score: 360 }, moscow: "could", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_Q3: QuarterlyPlan = {
  id: "plan_nav_q3_2026",
  quarter: Q3_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: NAV_Q3_GOALS,
  items: NAV_Q3_INITIATIVES,
  capacity: { unit: "story_points", total: 60, committed: NAV_Q3_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q3 2026 — Hitchhiker ────────────────────

const HH_Q3_GOALS: QuarterlyGoal[] = [
  { id: "hh_q3_g1", title: "Kubernetes migration", description: "Migrate all services to K8s", owningTeam: "Hitchhikers Team", kpiTarget: "100% services on K8s by Q3 end", weight: 5, quarter: Q3_2026, color: "#3b82f6" },
  { id: "hh_q3_g2", title: "Security hardening",   description: "SOC 2 Type II readiness and zero critical CVEs", owningTeam: "Hitchhikers Team", kpiTarget: "SOC 2 audit passed", weight: 5, quarter: Q3_2026, color: "#e5484d" },
];

const HH_Q3_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_q3_i1",
    featureRequestId: null,
    title: "K8s cluster setup & service migration",
    description: "Provision production K8s cluster and migrate the top 5 services",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q3_g1"],
    productArea: "Platform",
    status: "todo",
    priority: "urgent",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "hh_q3_i1", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 9, jobSize: 3, score: 3 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_q3_i2",
    featureRequestId: null,
    title: "SOC 2 Type II audit preparation",
    description: "Evidence gathering, control implementation, and external auditor engagement",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q3_g2"],
    productArea: "Platform",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "hh_q3_i2", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 10, jobSize: 4, score: 2.5 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_q3_i3",
    featureRequestId: null,
    title: "Secrets management overhaul",
    description: "Replace env-var secrets with Vault-based dynamic secrets",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q3_g2"],
    productArea: "Platform",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "hh_q3_i3", framework: "wsjf", rice: null, moscow: "should", wsjf: { costOfDelay: 7, jobSize: 2, score: 3.5 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_HH_Q3: QuarterlyPlan = {
  id: "plan_hh_q3_2026",
  quarter: Q3_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "draft",
  goals: HH_Q3_GOALS,
  items: HH_Q3_INITIATIVES,
  capacity: { unit: "story_points", total: 80, committed: HH_Q3_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q4 2026 — Navigators ────────────────────

const NAV_Q4_GOALS: QuarterlyGoal[] = [
  { id: "nav_q4_g1", title: "Enterprise launch",   description: "Ship enterprise tier with SSO, audit log, and permissions", owningTeam: "Navigators Team", kpiTarget: "5 enterprise deals closed", weight: 5, quarter: Q4_2026, color: "#f97316" },
  { id: "nav_q4_g2", title: "Year-end retention",  description: "Reduce churn below 3% with proactive success motions", owningTeam: "Navigators Team", kpiTarget: "Monthly churn < 3%", weight: 4, quarter: Q4_2026, color: "#8b5cf6" },
];

const NAV_Q4_INITIATIVES: RoadmapItem[] = [
  {
    id: "nav_q4_i1",
    featureRequestId: null,
    title: "SSO / SAML integration",
    description: "Login via Okta, Azure AD, and Google Workspace for enterprise teams",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q4_g1"],
    productArea: "Platform",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "nav_q4_i1", framework: "rice", rice: { reach: 200, impact: 5, confidence: 85, effort: 5, score: 170 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q4_i2",
    featureRequestId: null,
    title: "Audit log & activity trail",
    description: "Immutable log of all plan changes, role assignments, and share events",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q4_g1"],
    productArea: "Platform",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "nav_q4_i2", framework: "rice", rice: { reach: 150, impact: 4, confidence: 80, effort: 3, score: 160 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q4_i3",
    featureRequestId: null,
    title: "In-app NPS & churn signals",
    description: "Embed NPS survey and passive churn-risk detection in the product",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q4_g2"],
    productArea: "Growth",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "nav_q4_i3", framework: "rice", rice: { reach: 1000, impact: 3, confidence: 70, effort: 2, score: 1050 }, moscow: "should", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_Q4: QuarterlyPlan = {
  id: "plan_nav_q4_2026",
  quarter: Q4_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: NAV_Q4_GOALS,
  items: NAV_Q4_INITIATIVES,
  capacity: { unit: "story_points", total: 60, committed: NAV_Q4_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q4 2026 — Hitchhiker ────────────────────

const HH_Q4_GOALS: QuarterlyGoal[] = [
  { id: "hh_q4_g1", title: "Observability platform", description: "Full-stack observability with distributed tracing and unified dashboards", owningTeam: "Hitchhikers Team", kpiTarget: "MTTR < 15 min for P1", weight: 5, quarter: Q4_2026, color: "#14b8a6" },
  { id: "hh_q4_g2", title: "Disaster recovery",      description: "RTO < 1h and RPO < 15min across all production services", owningTeam: "Hitchhikers Team", kpiTarget: "DR drill passes RTO < 60 min", weight: 4, quarter: Q4_2026, color: "#f97316" },
];

const HH_Q4_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_q4_i1",
    featureRequestId: null,
    title: "Distributed tracing with OpenTelemetry",
    description: "Instrument all services with OTel and route traces to Grafana Tempo",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q4_g1"],
    productArea: "Platform",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "hh_q4_i1", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 8, jobSize: 2, score: 4 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_q4_i2",
    featureRequestId: null,
    title: "Multi-region failover",
    description: "Active-passive multi-region setup with automated failover and health checks",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q4_g2"],
    productArea: "Platform",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "hh_q4_i2", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 10, jobSize: 3, score: 3.3 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_HH_Q4: QuarterlyPlan = {
  id: "plan_hh_q4_2026",
  quarter: Q4_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "draft",
  goals: HH_Q4_GOALS,
  items: HH_Q4_INITIATIVES,
  capacity: { unit: "story_points", total: 80, committed: HH_Q4_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};
