import type {
  FeatureRequest,
  RoadmapItem,
  QuarterlyPlan,
  QuarterlyGoal,
} from "@/types";
import { makeQuarterRef } from "./constants";

// ── Global inbox seed (14 features, no teamId) ─
// These are the canonical feature requests shown in /inbox.
// useInboxStore uses these as its default state so the inbox
// always resets to this data when localStorage is cleared.

export const INBOX_SEED_REQUESTS: FeatureRequest[] = [
  {
    id: "f1", title: "Bulk CSV export for transaction reports", productArea: "Reporting", source: "customer",
    submittedBy: "Priya Nair, CFO @ Finstack", submittedAt: "2026-05-25",
    description: "Finance teams need to export large transaction datasets as CSV for reconciliation, auditing, and custom reporting in Excel or BI tools. Currently limited to 500 rows per export.",
    businessContext: "Blocking enterprise renewals worth ₹2.4Cr ARR. Four CFOs flagged this in QBRs this quarter.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://finstack.notion.so/csv-export-req", "https://support.example.com/tickets/4821"],
    votes: [
      { stakeholderId: "s_f1_0", stakeholderName: "Priya Nair, CFO @ Finstack",        comment: "We're manually extracting data row-by-row for month-end close — blocking our audit prep and taking 8 hours every cycle.", votedAt: "2026-05-25" },
      { stakeholderId: "s_f1_1", stakeholderName: "Ravi Kumar, Finance Lead @ ClearPay", comment: "Our reconciliation team hits the 500-row cap daily. We've resorted to splitting exports and stitching them back in Excel.", votedAt: "2026-05-25" },
      { stakeholderId: "s_f1_2", stakeholderName: "Deepa Menon, VP Finance @ RetailX",  comment: "Four of my enterprise clients flagged this in QBRs. One is already evaluating a competitor specifically over this gap.", votedAt: "2026-05-25" },
      { stakeholderId: "s_f1_3", stakeholderName: "Vikram Das, Enterprise Sales",        comment: "Lost two renewal conversations because the export limit came up. It's table stakes for any finance team.", votedAt: "2026-05-25" },
      { stakeholderId: "s_f1_4", stakeholderName: "Arun B., Controller @ FinopsHub",     comment: "500 rows doesn't cover a single day of transactions for us. We need full-history bulk export to meet compliance obligations.", votedAt: "2026-05-25" },
    ],
  },
  {
    id: "f2", title: "Webhook retry with exponential backoff", productArea: "API", source: "engineering",
    submittedBy: "Shankar P., Backend Lead", submittedAt: "2026-05-19",
    description: "When a merchant endpoint is temporarily unavailable, webhook events are dropped after a single retry. We need configurable retry schedules with exponential backoff to improve reliability.",
    businessContext: "Three enterprise merchants reported missed payment events last quarter. Reliability SLAs are at risk.",
    prioritySignal: "important", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://github.com/example/issues/1024"],
    votes: [
      { stakeholderId: "s_f2_0", stakeholderName: "Shankar P., Backend Lead",                comment: "We lost ₹40k in payment events last month due to single-retry failures. Ops manually replayed 200+ events after the fact.", votedAt: "2026-05-19" },
      { stakeholderId: "s_f2_1", stakeholderName: "Arun Dev, Platform Architect @ TechMerch", comment: "A flapping endpoint caused a 2-hour outage during a peak sale. Backoff would have degraded gracefully instead of hard-failing.", votedAt: "2026-05-19" },
      { stakeholderId: "s_f2_2", stakeholderName: "Deepika Nair, CTO @ D2C Brand",            comment: "Every dropped webhook is a missed order confirmation. Reliability is non-negotiable once you're above 10k orders/day.", votedAt: "2026-05-19" },
      { stakeholderId: "s_f2_3", stakeholderName: "Sai Rajan, Engineering Lead @ PayBridge",  comment: "We've built our own retry logic on top of the API as a workaround. This should be a platform primitive, not a per-customer hack.", votedAt: "2026-05-19" },
    ],
  },
  {
    id: "f3", title: "One-click payment link sharing via WhatsApp", productArea: "Payments", source: "customer",
    submittedBy: "Rohan Mehta, Sales Lead", submittedAt: "2026-05-12",
    description: "Merchants selling via WhatsApp Business need to share payment links directly inside the chat without copy-pasting. A native share button would streamline collection for D2C brands.",
    businessContext: "High-demand segment — 60% of our SMB merchants use WhatsApp as primary sales channel.",
    prioritySignal: "important", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null, supportingLinks: [],
    votes: [
      { stakeholderId: "s_f3_0", stakeholderName: "Rohan Mehta, Sales Lead",              comment: "SMB sellers are losing orders mid-conversation because the multi-step share process breaks the chat flow entirely.", votedAt: "2026-05-12" },
      { stakeholderId: "s_f3_1", stakeholderName: "Meena T., Owner @ GiftsByMeena",       comment: "I close 80% of my orders on WhatsApp. Copy-pasting links kills momentum right when the customer is ready to pay.", votedAt: "2026-05-12" },
      { stakeholderId: "s_f3_2", stakeholderName: "Shyam Sundar, Head of SMB Growth",     comment: "WhatsApp commerce is our fastest-growing segment. This is a must-have to stay competitive with Razorpay and Cashfree.", votedAt: "2026-05-12" },
      { stakeholderId: "s_f3_3", stakeholderName: "Lata Patel, Reseller @ HandmadeByLata", comment: "Customers ask for the link mid-chat. By the time I find and paste it, half have already dropped off.", votedAt: "2026-05-12" },
      { stakeholderId: "s_f3_4", stakeholderName: "Prashant V., Regional Sales @ SMB Desk", comment: "Every SMB merchant I onboard asks about this within the first week. It's the single biggest friction point in the segment.", votedAt: "2026-05-12" },
    ],
  },
  {
    id: "f4", title: "File Application Console Enhancement", productArea: "Developer Tools", source: "engineering",
    submittedBy: "Karan Desai, Platform Engineering Lead", submittedAt: "2026-05-05",
    description: "The file application console lacks essential developer tooling — no real-time log streaming, no structured error output, and no support for bulk file operations. Engineers are context-switching to external tools for tasks that should be native to the console.",
    businessContext: "Slowing down 3 active integrations and generating 15+ support escalations a month. Internal teams have flagged this as the top developer-experience gap for Q2.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://github.com/example/issues/2047", "https://internal.wiki/file-console-gaps"],
    votes: [
      { stakeholderId: "s_f4_0", stakeholderName: "Karan Desai, Platform Engineering Lead", comment: "We spend 40 minutes per deployment switching between the console and external log tools. Real-time streaming alone would save hours a week.", votedAt: "2026-05-05" },
      { stakeholderId: "s_f4_1", stakeholderName: "Sneha Iyer, Senior Developer @ FileOps", comment: "Structured error output is non-negotiable for debugging. Right now errors are buried in unformatted blobs — it's a productivity killer.", votedAt: "2026-05-05" },
      { stakeholderId: "s_f4_2", stakeholderName: "Arjun Pillai, DevOps Engineer",           comment: "Bulk file operations are manual and error-prone. One misfire last quarter corrupted a staging environment and cost us a full day.", votedAt: "2026-05-05" },
      { stakeholderId: "s_f4_3", stakeholderName: "Meera Nandan, Integration Engineer",      comment: "Every new integration onboarding involves a workaround for the console's limitations. This is the first thing engineers complain about.", votedAt: "2026-05-05" },
      { stakeholderId: "s_f4_4", stakeholderName: "Rahul Srinivasan, VP Engineering",        comment: "This is blocking two enterprise integrations we committed to for Q2. It needs to be fixed before we can unblock those teams.", votedAt: "2026-05-05" },
    ],
  },
  {
    id: "f5", title: "Smart dispute auto-categorisation", productArea: "Disputes", source: "internal",
    submittedBy: "Ananya S., Head of Support", submittedAt: "2026-04-28",
    description: "Support agents manually tag every dispute by type (fraud, product, service). An ML-based tagger trained on historical resolutions could auto-classify disputes and route them to the right queue.",
    businessContext: "Support handles 400+ disputes/month. Auto-categorisation could cut resolution time by 35% and reduce agent cost.",
    prioritySignal: "nice_to_have", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null, supportingLinks: [],
    votes: [
      { stakeholderId: "s_f5_0", stakeholderName: "Ananya S., Head of Support",            comment: "Manual tagging is error-prone — wrong categories delay resolutions by 2–3 days and spike our SLA breach rate.", votedAt: "2026-04-28" },
      { stakeholderId: "s_f5_1", stakeholderName: "Karan Malhotra, Customer Success Lead", comment: "Auto-categorisation would let us route disputes instantly instead of having an agent triage every single one before routing.", votedAt: "2026-04-28" },
      { stakeholderId: "s_f5_2", stakeholderName: "Nidhi Jain, Operations Manager",        comment: "We handle 400+ disputes a month. Even a 30% auto-classification rate would free up meaningful agent capacity.", votedAt: "2026-04-28" },
    ],
  },
  {
    id: "f6", title: "Saved card management for returning customers", productArea: "Payments", source: "customer",
    submittedBy: "Multiple — 34 support tickets", submittedAt: "2026-04-14",
    description: "Returning customers want to manage their saved cards — view, delete, or set a default — without re-entering details each transaction. Currently there's no self-serve card vault UI.",
    businessContext: "Top requested feature in NPS surveys for 3 consecutive quarters. Directly impacts checkout conversion rate.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://nps-dashboard.example.com/q1-themes"],
    votes: [
      { stakeholderId: "s_f6_0", stakeholderName: "Ritika Sharma, Enterprise Customer",           comment: "I've entered my card details 12 times this month. A vault would save 30 seconds per checkout — and I'd actually complete more purchases.", votedAt: "2026-04-14" },
      { stakeholderId: "s_f6_1", stakeholderName: "Pavan Kumar, VP Product @ FastCart",           comment: "Cart abandonment at the payment step is 34% above industry average. We attribute this directly to the lack of saved cards.", votedAt: "2026-04-14" },
      { stakeholderId: "s_f6_2", stakeholderName: "Sonal Mehta, NPS Respondent",                  comment: "This is the single feature I'd pay a premium for. Every checkout feels like the first time, which erodes trust in the platform.", votedAt: "2026-04-14" },
      { stakeholderId: "s_f6_3", stakeholderName: "Arjun Reddy, Head of Checkout @ BigBazaarOnline", comment: "Our A/B prototype with saved cards showed a 22% lift in completed transactions. The data is unambiguous.", votedAt: "2026-04-14" },
      { stakeholderId: "s_f6_4", stakeholderName: "Isha Nair, Customer Experience Lead",          comment: "43% of our repeat-customer complaints this quarter were about re-entering payment details. Top NPS driver by far.", votedAt: "2026-04-14" },
      { stakeholderId: "s_f6_5", stakeholderName: "Dev Mehta, VP Engineering @ ShopLocal",        comment: "We've jury-rigged browser autofill as a workaround, but it's fragile and breaks on mobile. Native card vault is the right fix.", votedAt: "2026-04-14" },
    ],
  },
  {
    id: "f7", title: "Refund SLA tracker with merchant-facing status page", productArea: "Disputes", source: "internal",
    submittedBy: "Customer Success Team", submittedAt: "2026-04-01",
    description: "Merchants have no visibility into refund processing timelines. A status page showing refund stages (initiated → bank processing → credited) would reduce support volume around refund queries.",
    businessContext: "Refund-related tickets account for 28% of CS volume. A status page alone could deflect ~300 tickets/month.",
    prioritySignal: "important", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null, supportingLinks: [],
    votes: [
      { stakeholderId: "s_f7_0", stakeholderName: "Customer Success Team",                   comment: "We field 300+ 'where's my refund' tickets monthly. A self-serve status page would deflect nearly all of them instantly.", votedAt: "2026-04-01" },
      { stakeholderId: "s_f7_1", stakeholderName: "Madhuri P., Merchant @ HomeBrew",          comment: "Had to email every customer individually during a bank outage. A live refund tracker would have handled that automatically.", votedAt: "2026-04-01" },
      { stakeholderId: "s_f7_2", stakeholderName: "Arjun Kapoor, CS Agent",                   comment: "25% of my shift is answering refund status questions. A status page would free me to work on higher-value issues.", votedAt: "2026-04-01" },
      { stakeholderId: "s_f7_3", stakeholderName: "Preethi R., Operations Lead @ PayReceive", comment: "Merchants need transparency into refund timelines to manage their own customers. Right now they're completely in the dark.", votedAt: "2026-04-01" },
    ],
  },
  {
    id: "f8", title: "API rate limit visibility in dashboard", productArea: "API", source: "engineering",
    submittedBy: "Developer community forum", submittedAt: "2026-03-20",
    description: "Developers hitting rate limits get opaque 429 errors with no visibility into current usage vs limits. The dashboard should show live API consumption, remaining quota, and reset windows.",
    businessContext: "Frequent complaint in developer community forum and onboarding calls. Affects developer experience score.",
    prioritySignal: "important", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://community.example.com/rate-limit-thread"],
    votes: [
      { stakeholderId: "s_f8_0", stakeholderName: "Suhail Ahmed, Developer @ Integrations.io",  comment: "Hit a 429 with zero warning and no dashboard indicator. Spent 45 minutes diagnosing an outage that was just a rate limit.", votedAt: "2026-03-20" },
      { stakeholderId: "s_f8_1", stakeholderName: "Devraj N., Lead Engineer @ StartupPay",      comment: "Our monitoring is blind to rate limit headroom. We discover throttling after the fact, never before it causes an incident.", votedAt: "2026-03-20" },
      { stakeholderId: "s_f8_2", stakeholderName: "Ankit Shah, Platform Engineer @ APIConnect", comment: "Live consumption with reset windows is table stakes for any API-first product. This is basic developer tooling.", votedAt: "2026-03-20" },
      { stakeholderId: "s_f8_3", stakeholderName: "Pooja Jain, Developer Community Moderator",  comment: "Rate limit confusion is the most-asked topic in our forum. Visibility alone would cut 40% of support escalations.", votedAt: "2026-03-20" },
    ],
  },
  {
    id: "f9", title: "Scheduled payouts for marketplace sellers", productArea: "Payouts", source: "customer",
    submittedBy: "Vikram Das, Enterprise Sales", submittedAt: "2026-03-05",
    description: "Marketplace operators need to schedule payouts to sellers on weekly or monthly cycles rather than triggering them manually. This includes configurable payout dates, hold periods, and auto-split rules.",
    businessContext: "Blocking a ₹1.8Cr ACV marketplace deal. Competitor already offers scheduled payouts.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://docs.example.com/payouts/scheduling"],
    votes: [
      { stakeholderId: "s_f9_0", stakeholderName: "Vikram Das, Enterprise Sales",                    comment: "A ₹1.8Cr ACV deal is blocked entirely on this. The competitor they're evaluating already ships weekly scheduled payouts.", votedAt: "2026-03-05" },
      { stakeholderId: "s_f9_1", stakeholderName: "Sai Gopal, CTO @ MarketNow",                      comment: "Our sellers expect payouts every Friday. Manual triggering has failed twice this quarter, directly causing seller churn.", votedAt: "2026-03-05" },
      { stakeholderId: "s_f9_2", stakeholderName: "Neha Gupta, Finance Lead @ HubSell",              comment: "200+ sellers, manual payout runs each cycle — takes a full workday. Automation would reclaim that time entirely.", votedAt: "2026-03-05" },
      { stakeholderId: "s_f9_3", stakeholderName: "Rahul Kapoor, Head of Marketplace @ BazaarPro",   comment: "Scheduled payouts are how we build seller trust. Right now we're managing expectations over Slack instead of shipping a feature.", votedAt: "2026-03-05" },
      { stakeholderId: "s_f9_4", stakeholderName: "Aisha Mehta, Seller @ CraftCircle",               comment: "I plan inventory purchases around payout dates. When a manual run gets delayed, my whole supply chain is affected.", votedAt: "2026-03-05" },
    ],
  },
  {
    id: "f10", title: "Dark mode for merchant dashboard", productArea: "Dashboard", source: "customer",
    submittedBy: "NPS Responses Q1 — 47 mentions", submittedAt: "2026-02-18",
    description: "Many merchants operate late-night shifts in warehouses and prefer dark UI to reduce eye strain. A system-preference-aware dark mode would improve usability and NPS among high-volume merchants.",
    businessContext: "47 unprompted NPS mentions in Q1. Low engineering effort relative to sentiment impact.",
    prioritySignal: "nice_to_have", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null, supportingLinks: [],
    votes: [
      { stakeholderId: "s_f10_0", stakeholderName: "Kavya Reddy, Warehouse Supervisor @ NightOps",  comment: "My team runs 10pm–6am shifts. The bright white dashboard is the first complaint every single night — eye strain is real.", votedAt: "2026-02-18" },
      { stakeholderId: "s_f10_1", stakeholderName: "Amit Joshi, NPS Respondent",                    comment: "Dark mode is table stakes for any modern B2B tool. This would genuinely make me enjoy using the product more.", votedAt: "2026-02-18" },
      { stakeholderId: "s_f10_2", stakeholderName: "Sriram V., Operations Manager @ 24x7Logistics", comment: "Night-shift staff use mobile with dark mode enabled just to avoid the bright UI. Please build this natively.", votedAt: "2026-02-18" },
      { stakeholderId: "s_f10_3", stakeholderName: "Deepa Kumar, Merchant @ LateNightMart",         comment: "47 of us mentioned this unprompted in the Q1 NPS survey. It's a recurring pain point, not a niche request.", votedAt: "2026-02-18" },
      { stakeholderId: "s_f10_4", stakeholderName: "Rajan P., Finance Controller @ NightOwlPharma", comment: "I do month-end close at midnight. A dark interface would reduce fatigue and help me work more accurately during late sessions.", votedAt: "2026-02-18" },
    ],
  },
  {
    id: "f11", title: "Inbox DLQ Capability", productArea: "Platform", source: "engineering",
    submittedBy: "Platform Engineering Team", submittedAt: "2026-05-27",
    description: "Add Dead Letter Queue support, RSDs (Retry Strategy Definitions), and Inbox Operator tooling to Hub Inbox. Enables developers to handle failed inbox messages without manual platform team intervention.",
    businessContext: "All failed inbox messages currently require platform team intervention to investigate and replay. This is a growing support bottleneck — averaging 20+ escalations a week — and slows incident resolution across Hub tenants.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://github.com/example/issues/3102", "https://internal.wiki/hub-inbox-dlq-rfc"],
    votes: [
      { stakeholderId: "s_f11_0", stakeholderName: "Suresh Nair, Staff Engineer @ Hub Platform", comment: "We're manually replaying failed messages multiple times a week. DLQ support would let app teams own their own failure handling without paging us.", votedAt: "2026-05-27" },
      { stakeholderId: "s_f11_1", stakeholderName: "Divya Krishnan, Engineering Manager",         comment: "The lack of RSDs means every retry strategy is bespoke per application. Standardising this would cut incident triage time by at least half.", votedAt: "2026-05-27" },
      { stakeholderId: "s_f11_2", stakeholderName: "Aditya Rao, Backend Developer @ TenantOps",  comment: "Every time a message fails we raise a ticket and wait. With Inbox Operator tooling we could self-serve investigations and replays immediately.", votedAt: "2026-05-27" },
      { stakeholderId: "s_f11_3", stakeholderName: "Priya Venkat, SRE Lead",                     comment: "Hub Inbox failures are in our top-5 on-call triggers. DLQ visibility would let us detect and resolve issues before they escalate to production incidents.", votedAt: "2026-05-27" },
    ],
  },
  {
    id: "f12", title: "Credentials Management", productArea: "Security", source: "engineering",
    submittedBy: "Dia Platform Team", submittedAt: "2026-05-24",
    description: "Secure handling of secrets and credentials for Hub applications via Dia. Provides a managed credential store that applications can reference without embedding secrets in manifests or source code.",
    businessContext: "Secrets embedded in manifests are a security liability flagged in the last internal audit. Several Hub applications are currently non-compliant with the organisation's secret management policy, creating audit and breach risk.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://internal.wiki/dia-credentials-spec", "https://github.com/example/issues/2891"],
    votes: [
      { stakeholderId: "s_f12_0", stakeholderName: "Rohan Joshi, Security Architect",         comment: "Hardcoded secrets in manifests are the number-one finding in our quarterly security reviews. This needs to be solved at the platform level, not per-app.", votedAt: "2026-05-24" },
      { stakeholderId: "s_f12_1", stakeholderName: "Ananya Rao, Compliance Lead",             comment: "We're carrying audit risk on every Hub application that still embeds credentials. A managed credential store would close the gap across the board.", votedAt: "2026-05-24" },
      { stakeholderId: "s_f12_2", stakeholderName: "Kiran Mehta, Senior Developer @ AppHub", comment: "Rotating secrets manually across manifests is error-prone and has caused two outages. A centralised store with automatic rotation would remove that risk entirely.", votedAt: "2026-05-24" },
      { stakeholderId: "s_f12_3", stakeholderName: "Siddharth V., DevOps Engineer",          comment: "Without managed credentials, every CI pipeline has its own bespoke secret injection. Dia-native support would standardise and secure the entire deploy chain.", votedAt: "2026-05-24" },
      { stakeholderId: "s_f12_4", stakeholderName: "Nisha Patel, VP Engineering",            comment: "This is a pre-requisite for two enterprise customer certifications we're targeting in Q3. We can't proceed without it.", votedAt: "2026-05-24" },
    ],
  },
  {
    id: "f13", title: "Customer Onboarding Enablement", productArea: "Customer Success", source: "internal",
    submittedBy: "Preethi Sharma, Head of Customer Success", submittedAt: "2026-05-20",
    description: "Dedicated bandwidth to help customers onboard onto Hub applications. Root cause of onboarding friction is poor developer experience — this initiative bridges the gap with guided onboarding, enablement support, and activation tracking.",
    businessContext: "Time-to-first-value for new Hub customers is averaging 6 weeks, double the 3-week target. Onboarding drop-off is the top contributor to early-stage churn and delayed revenue recognition.",
    prioritySignal: "important", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://internal.wiki/onboarding-metrics-q1", "https://internal.notion.so/hub-activation-report"],
    votes: [
      { stakeholderId: "s_f13_0", stakeholderName: "Preethi Sharma, Head of Customer Success", comment: "We're losing customers in the first 30 days not because the product is bad, but because the onboarding path is unclear. Guided enablement would change that.", votedAt: "2026-05-20" },
      { stakeholderId: "s_f13_1", stakeholderName: "Lakshmi R., Customer Success Manager",     comment: "I spend 60% of my time filling gaps in the onboarding experience manually. Structured activation tracking would let me focus on relationship-building instead.", votedAt: "2026-05-20" },
      { stakeholderId: "s_f13_2", stakeholderName: "Arvind Kumar, New Customer @ FinBridge",   comment: "We went 4 weeks without a working Hub integration because we couldn't figure out the correct setup sequence. A guided flow would have cut that to days.", votedAt: "2026-05-20" },
      { stakeholderId: "s_f13_3", stakeholderName: "Tanvi Mehta, Solutions Engineer",          comment: "Activation data is scattered across spreadsheets and Slack threads. A proper tracking layer would give us early signals on at-risk accounts before they churn.", votedAt: "2026-05-20" },
    ],
  },
  {
    id: "f14", title: "PCI Data Management", productArea: "Compliance", source: "internal",
    submittedBy: "Compliance & Security Team", submittedAt: "2026-05-22",
    description: "Establish a framework for managing PCI-scoped data within Hub applications, including data classification, access controls, audit logging, and tokenisation support for cardholder data environments.",
    businessContext: "PCI DSS v4.0 compliance deadline is approaching and formal data management controls are required. Three enterprise customers are blocked from production go-live pending PCI certification of the Hub platform.",
    prioritySignal: "critical", status: "new", tags: [], goalIds: [], comments: [], mergedFromIds: [], externalRef: null,
    supportingLinks: ["https://internal.wiki/pci-dss-v4-readiness", "https://internal.notion.so/hub-pci-gap-analysis"],
    votes: [
      { stakeholderId: "s_f14_0", stakeholderName: "Vikram Pillai, Chief Compliance Officer",      comment: "PCI DSS v4.0 requires controls we don't have today. Without this we cannot certify Hub for cardholder data environments — full stop.", votedAt: "2026-05-22" },
      { stakeholderId: "s_f14_1", stakeholderName: "Ananya Rao, Compliance Lead",                  comment: "The gap analysis shows 7 open controls. Data classification and access controls are the two highest-risk items we need to close first.", votedAt: "2026-05-22" },
      { stakeholderId: "s_f14_2", stakeholderName: "Rajesh Kumar, Enterprise Account @ PaySecure", comment: "Our legal team has put our Hub go-live on hold until PCI certification is confirmed. This is blocking ₹3Cr in contracted ARR.", votedAt: "2026-05-22" },
      { stakeholderId: "s_f14_3", stakeholderName: "Sonal Iyer, Security Engineer",                comment: "Without tokenisation support, every team touching cardholder data is building their own controls. Standardising at the platform level is the only scalable fix.", votedAt: "2026-05-22" },
      { stakeholderId: "s_f14_4", stakeholderName: "Deepak Nair, CTO @ CardVault Inc",             comment: "We chose Hub on the premise that PCI compliance would be handled at the infrastructure layer. That expectation needs to be met before we can go live.", votedAt: "2026-05-22" },
    ],
  },
];

const Q2_2026 = makeQuarterRef(2026, 2);
const Q3_2026 = makeQuarterRef(2026, 3);
const Q4_2026 = makeQuarterRef(2026, 4);

// ── Feature Requests (Inbox) ───────────────

export const SEED_REQUESTS: FeatureRequest[] = [
  {
    id: "req_001",
    teamId: "team_navigators",
    title: "Bulk status update for feature requests",
    description: "PMs need to triage 50+ items at once. Currently requires clicking each row individually.",
    businessContext: "Saves ~2 hours per planning cycle",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["triage", "bulk-actions", "inbox"],
    productArea: "Core Product",
    goalIds: ["goal_001"],
    submittedBy: "Sarah K.",
    submittedAt: "2026-05-20T09:00:00Z",
    votes: [
      { stakeholderId: "u_2", stakeholderName: "Marcus T.", comment: "Critical for our workflow", votedAt: "2026-05-21T10:00:00Z" },
      { stakeholderId: "u_3", stakeholderName: "Priya N.", comment: null, votedAt: "2026-05-21T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_002",
    teamId: "team_navigators",
    title: "WSJF scoring framework support",
    description: "Our team uses Weighted Shortest Job First for hardware-adjacent roadmap items. RICE doesn't map well.",
    businessContext: "Unblocks 3 PMs who currently maintain separate spreadsheets",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["scoring", "frameworks", "wsjf"],
    productArea: "Core Product",
    goalIds: ["goal_001"],
    submittedBy: "James R.",
    submittedAt: "2026-05-18T11:30:00Z",
    votes: [
      { stakeholderId: "u_4", stakeholderName: "Anita L.", comment: "Already on the roadmap?", votedAt: "2026-05-19T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_003",
    teamId: "team_navigators",
    title: "Shareable read-only roadmap view",
    description: "Need to send a polished roadmap link to leadership without giving them edit access.",
    businessContext: "Eliminates the quarterly slide deck rebuild",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["roadmap", "sharing", "stakeholders"],
    productArea: "Roadmap Planning",
    goalIds: ["goal_002"],
    submittedBy: "VP Product",
    submittedAt: "2026-05-15T08:00:00Z",
    votes: [
      { stakeholderId: "u_5", stakeholderName: "Tomás V.", comment: "Would save our leadership prep", votedAt: "2026-05-16T10:00:00Z" },
      { stakeholderId: "u_6", stakeholderName: "Hana M.", comment: "Yes please", votedAt: "2026-05-16T11:00:00Z" },
      { stakeholderId: "u_7", stakeholderName: "David P.", comment: null, votedAt: "2026-05-17T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_004",
    teamId: "team_navigators",
    title: "Linear integration — push initiatives as projects",
    description: "After approving the plan, we manually recreate everything in Linear. One-click push would save hours.",
    businessContext: "~4 hours saved per planning cycle per PM",
    source: "internal",
    prioritySignal: "critical",
    status: "new",
    tags: ["integrations", "linear", "automation"],
    productArea: "Integrations",
    goalIds: ["goal_003"],
    submittedBy: "Eng Lead",
    submittedAt: "2026-05-22T14:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_005",
    teamId: "team_navigators",
    title: "Capacity bar in roadmap view",
    description: "We keep over-committing. A visual capacity meter that updates as items are added would prevent this.",
    businessContext: "Prevents over-commitment before plan is locked",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["roadmap", "capacity", "planning"],
    productArea: "Roadmap Planning",
    goalIds: ["goal_002"],
    submittedBy: "Alex Chen",
    submittedAt: "2026-05-23T09:00:00Z",
    votes: [
      { stakeholderId: "u_8", stakeholderName: "Lena B.", comment: "Essential", votedAt: "2026-05-23T10:30:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_006",
    teamId: "team_navigators",
    title: "Email digest for voting round outcomes",
    description: "PMs should receive a summary when a voting round closes, not have to manually check.",
    businessContext: "Reduces time lost to manual follow-up",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "archived",
    tags: ["notifications", "email", "voting"],
    productArea: "Notifications",
    goalIds: [],
    submittedBy: "Priya N.",
    submittedAt: "2026-05-10T16:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "req_007",
    teamId: "team_navigators",
    title: "Keyboard shortcut to create new initiative",
    description: "Power users want to press 'C' anywhere in the app to open the new initiative modal.",
    businessContext: "Matches Linear UX — PMs familiar with this pattern",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "triaged",
    tags: ["keyboard", "ux", "shortcuts"],
    productArea: "Core Product",
    goalIds: [],
    submittedBy: "Zoe K.",
    submittedAt: "2026-05-12T13:00:00Z",
    votes: [
      { stakeholderId: "u_9", stakeholderName: "Alex Chen", comment: "100% agree", votedAt: "2026-05-13T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
];

// ── Hitchhiker Inbox Requests ──────────────

export const SEED_REQUESTS_HITCHHIKER: FeatureRequest[] = [
  {
    id: "hh_req_001",
    teamId: "team_hitchhiker",
    title: "Public system status page with real-time incident updates",
    description: "When we have an outage, customers flood support with tickets before we can communicate anything. A live status page with incident timelines would let customers self-serve and reduce support load during incidents.",
    businessContext: "Support ticket volume spikes 5x during outages. Last quarter's P1 cost ~$40K in support hours.",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["reliability", "communication", "incidents", "transparency"],
    productArea: "Platform",
    goalIds: ["hh_goal_001"],
    submittedBy: "VP Customer Success",
    submittedAt: "2026-05-03T09:00:00Z",
    votes: [
      { stakeholderId: "u_hh_1", stakeholderName: "Ravi M.", comment: "Every customer asks us for this during incidents", votedAt: "2026-05-04T10:00:00Z" },
      { stakeholderId: "u_hh_2", stakeholderName: "Selin A.", comment: "Agreed — we look unprofessional without one", votedAt: "2026-05-04T14:00:00Z" },
      { stakeholderId: "u_hh_3", stakeholderName: "Tom B.", comment: null, votedAt: "2026-05-05T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_002",
    teamId: "team_hitchhiker",
    title: "API rate limit visibility and self-service quota management",
    description: "Customers hitting rate limits get a generic 429 with no context on their current usage, reset times, or how to request higher limits. We need a dashboard where they can monitor consumption and request quota increases.",
    businessContext: "Rate limit complaints are our #3 support category. Several enterprise customers threatened churn in Q1.",
    source: "customer",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["api", "rate-limiting", "developer-experience", "self-service"],
    productArea: "Platform",
    goalIds: ["hh_goal_002"],
    submittedBy: "Priya N. (Acme Corp)",
    submittedAt: "2026-05-06T11:30:00Z",
    votes: [
      { stakeholderId: "u_hh_4", stakeholderName: "James R.", comment: "We hit this weekly — our integration team is frustrated", votedAt: "2026-05-07T09:00:00Z" },
      { stakeholderId: "u_hh_5", stakeholderName: "Yuki T.", comment: "Would unlock our high-frequency use case", votedAt: "2026-05-07T11:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_003",
    teamId: "team_hitchhiker",
    title: "Self-service environment provisioning for engineers",
    description: "Engineers currently wait 2–4 days for DevOps to provision a new staging environment. We need a self-service portal where engineers can spin up isolated environments from a template in under 10 minutes.",
    businessContext: "New engineers lose ~3 days in their first week waiting on environment setup. Cross-team dependencies add more delays.",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["developer-experience", "environments", "self-service", "onboarding"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_002"],
    submittedBy: "Eng Lead",
    submittedAt: "2026-05-08T10:00:00Z",
    votes: [
      { stakeholderId: "u_hh_6", stakeholderName: "Dana K.", comment: "This is the #1 complaint in our retrospectives", votedAt: "2026-05-09T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_004",
    teamId: "team_hitchhiker",
    title: "Webhook retry logic and dead-letter queue",
    description: "When our API delivers webhook events and the customer endpoint is temporarily unavailable, the event is dropped silently. We need configurable retry logic with exponential back-off and a dead-letter queue customers can replay from.",
    businessContext: "We've lost customer trust after silent webhook failures caused data inconsistencies in downstream systems.",
    source: "customer",
    prioritySignal: "critical",
    status: "new",
    tags: ["webhooks", "reliability", "api", "events"],
    productArea: "Platform",
    goalIds: ["hh_goal_001"],
    submittedBy: "Mateo L. (BuildFast)",
    submittedAt: "2026-05-10T14:00:00Z",
    votes: [
      { stakeholderId: "u_hh_7", stakeholderName: "Anita B.", comment: "This caused a P2 for us last month", votedAt: "2026-05-11T10:00:00Z" },
      { stakeholderId: "u_hh_8", stakeholderName: "Chen W.", comment: "Our data sync relies on reliable webhooks", votedAt: "2026-05-11T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_005",
    teamId: "team_hitchhiker",
    title: "API deprecation notices and advance warning emails",
    description: "The last time we deprecated an endpoint, customers only found out when their integrations broke in production. We need a formal deprecation process: in-response headers, dashboard warnings, and 90-day email notices before any endpoint is removed.",
    businessContext: "Two enterprise customers escalated to exec level after silent API deprecations broke their production integrations.",
    source: "customer",
    prioritySignal: "important",
    status: "triaged",
    tags: ["api", "deprecation", "developer-experience", "communication"],
    productArea: "Platform",
    goalIds: ["hh_goal_002"],
    submittedBy: "Lena B. (Dataflow)",
    submittedAt: "2026-05-11T09:00:00Z",
    votes: [
      { stakeholderId: "u_hh_9", stakeholderName: "Sam R.", comment: "Industry standard practice — we should have had this from day one", votedAt: "2026-05-12T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_006",
    teamId: "team_hitchhiker",
    title: "Automated dependency vulnerability scanning in CI",
    description: "Our current security review process is manual and quarterly. We need automated scanning for vulnerable dependencies in every pull request, with severity gates that block merges on critical CVEs.",
    businessContext: "Security audit flagged 14 unpatched CVEs in Q1. Manual review misses newly disclosed vulnerabilities between cycles.",
    source: "internal",
    prioritySignal: "critical",
    status: "triaged",
    tags: ["security", "ci", "dependencies", "vulnerability-scanning"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_001"],
    submittedBy: "Security Lead",
    submittedAt: "2026-05-12T08:00:00Z",
    votes: [
      { stakeholderId: "u_hh_10", stakeholderName: "Jordan S.", comment: "Should be mandatory — we're headed to SOC 2 and this is a requirement", votedAt: "2026-05-13T10:00:00Z" },
      { stakeholderId: "u_hh_11", stakeholderName: "Morgan L.", comment: null, votedAt: "2026-05-13T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_007",
    teamId: "team_hitchhiker",
    title: "API usage analytics dashboard for developers",
    description: "Customers building on our platform have no visibility into which endpoints they call most, error rates by endpoint, or latency trends over time. A usage dashboard would help them optimise their integrations and debug issues faster.",
    businessContext: "Reduces support tickets from developers investigating their own integration health. Competitors (Stripe, Twilio) all offer this.",
    source: "customer",
    prioritySignal: "important",
    status: "new",
    tags: ["api", "analytics", "developer-experience", "observability"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_002", "hh_goal_003"],
    submittedBy: "Product Marketing",
    submittedAt: "2026-05-13T11:00:00Z",
    votes: [
      { stakeholderId: "u_hh_12", stakeholderName: "Zoe K.", comment: "I've had three sales calls this month where this was asked about", votedAt: "2026-05-14T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_008",
    teamId: "team_hitchhiker",
    title: "p95 latency SLO alerts and dashboard for platform teams",
    description: "We don't have any automated alerting when our p95 latency degrades — we only notice when customers complain. We need dashboards showing latency by endpoint over time, with PagerDuty alerts when p95 exceeds our 200ms SLO.",
    businessContext: "Latency regressions currently go undetected for days. MTTR is high because we're always reactive, never proactive.",
    source: "internal",
    prioritySignal: "important",
    status: "new",
    tags: ["observability", "latency", "slo", "alerting"],
    productArea: "Platform",
    goalIds: ["hh_goal_001", "hh_goal_003"],
    submittedBy: "SRE Lead",
    submittedAt: "2026-05-15T09:00:00Z",
    votes: [
      { stakeholderId: "u_hh_13", stakeholderName: "Ravi M.", comment: "This is foundational — hard to justify the Q3 reliability goal without it", votedAt: "2026-05-15T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_009",
    teamId: "team_hitchhiker",
    title: "Interactive API reference with live code examples",
    description: "Our current API docs are static Markdown. Developers have to copy snippets into Postman to try anything. We need interactive docs (like Stripe's) where they can authenticate and execute real API calls from the browser.",
    businessContext: "Time-to-first-API-call is currently 3–4 hours. Interactive docs could cut that to under 30 minutes, improving conversion from trial to paid.",
    source: "customer",
    prioritySignal: "important",
    status: "new",
    tags: ["documentation", "developer-experience", "api", "onboarding"],
    productArea: "Developer Experience",
    goalIds: ["hh_goal_002"],
    submittedBy: "Growth Team",
    submittedAt: "2026-05-17T10:00:00Z",
    votes: [
      { stakeholderId: "u_hh_14", stakeholderName: "Alex C.", comment: "Our trial-to-paid conversion is below benchmark — docs friction is one culprit", votedAt: "2026-05-18T09:00:00Z" },
      { stakeholderId: "u_hh_15", stakeholderName: "Priya N.", comment: "Would have saved me hours of debugging on day one", votedAt: "2026-05-18T11:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_010",
    teamId: "team_hitchhiker",
    title: "Canary deployment support for API rollouts",
    description: "We currently do big-bang deployments and roll back manually when something breaks. We need a canary deployment pipeline that routes a small percentage of traffic to a new release before full rollout, with automatic rollback on error-rate thresholds.",
    businessContext: "Two of our last three P1 incidents were caused by full-traffic deployments of regressions that canary traffic would have caught.",
    source: "internal",
    prioritySignal: "important",
    status: "triaged",
    tags: ["reliability", "deployment", "canary", "platform"],
    productArea: "Platform",
    goalIds: ["hh_goal_001"],
    submittedBy: "Platform Lead",
    submittedAt: "2026-05-19T14:00:00Z",
    votes: [
      { stakeholderId: "u_hh_16", stakeholderName: "Dana K.", comment: "Would have prevented the March incident", votedAt: "2026-05-20T09:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_011",
    teamId: "team_hitchhiker",
    title: "Infrastructure cost attribution by team and service",
    description: "Our cloud bill is growing 40% quarter-over-quarter but we have no visibility into which team or service is driving costs. We need per-service cost dashboards with weekly team-level summaries so engineering leads can make informed build-vs-optimise decisions.",
    businessContext: "Q1 cloud spend was 18% over budget. Finance is asking engineering to present a cost-reduction plan but we have no data to back decisions.",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "new",
    tags: ["cost", "platform", "observability", "finance"],
    productArea: "Platform",
    goalIds: [],
    submittedBy: "CFO",
    submittedAt: "2026-05-21T10:00:00Z",
    votes: [
      { stakeholderId: "u_hh_17", stakeholderName: "Morgan L.", comment: "Finance flagged this as urgent — worth prioritising", votedAt: "2026-05-21T14:00:00Z" },
    ],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
  {
    id: "hh_req_012",
    teamId: "team_hitchhiker",
    title: "Automated on-call handoff notes from incident history",
    description: "On-call engineers currently write handoff notes manually at the end of each shift. The information already exists in our incident tracking — we should auto-generate a structured summary of open incidents, recent changes, and known risks for the incoming on-call.",
    businessContext: "Incomplete handoffs have contributed to two incidents where the incoming on-call lacked context. Manual notes take ~45 minutes per handoff.",
    source: "internal",
    prioritySignal: "nice_to_have",
    status: "archived",
    tags: ["on-call", "developer-experience", "automation", "reliability"],
    productArea: "Developer Experience",
    goalIds: [],
    submittedBy: "SRE Team",
    submittedAt: "2026-05-10T16:00:00Z",
    votes: [],
    comments: [],
    supportingLinks: [],
    mergedFromIds: [],
    externalRef: null,
  },
];

// ── Quarterly Goals ────────────────────────

const SEED_GOALS: QuarterlyGoal[] = [
  {
    id: "goal_001",
    title: "Deliver MVP scoring engine",
    description: "Launch RICE, MoSCoW, WSJF scoring in a single view",
    owningTeam: "Product",
    kpiTarget: "WAU > 60% of registered PMs",
    weight: 5,
    quarter: Q2_2026,
    color: "#5e5ce6",
  },
  {
    id: "goal_002",
    title: "Stakeholder-ready roadmap output",
    description: "Shareable, polished roadmap view replacing slide decks",
    owningTeam: "Product",
    kpiTarget: "NPS > 50 at 3 months",
    weight: 4,
    quarter: Q2_2026,
    color: "#30a46c",
  },
  {
    id: "goal_003",
    title: "Jira & Linear integrations",
    description: "One-click push of approved initiatives to execution tools",
    owningTeam: "Engineering",
    kpiTarget: "40% of plans use integration",
    weight: 3,
    quarter: Q2_2026,
    color: "#f5a623",
  },
];

// ── Roadmap Initiatives ────────────────────

export const SEED_INITIATIVES: RoadmapItem[] = [
  {
    id: "init_001",
    teamId: "team_navigators",
    featureRequestId: "req_001",
    title: "Bulk triage actions",
    description: "Multi-select + bulk status/tag operations in inbox",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_001"],
    productArea: "Core Product",
    status: "in_progress",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_001",
      framework: "rice",
      rice: { reach: 500, impact: 2, confidence: 80, effort: 2, score: 400 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-20T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_002",
    teamId: "team_navigators",
    featureRequestId: "req_002",
    title: "WSJF scoring framework",
    description: "Full WSJF scoring with cost-of-delay and job-size inputs",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_001"],
    productArea: "Core Product",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_002",
      framework: "rice",
      rice: { reach: 300, impact: 2, confidence: 90, effort: 3, score: 180 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-19T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [{ initiativeId: "init_001", type: "blocked_by" }],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-18T11:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_003",
    teamId: "team_navigators",
    featureRequestId: "req_003",
    title: "Shareable read-only roadmap",
    description: "Public link generation, password protection, live-updating view",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_002"],
    productArea: "Roadmap Planning",
    status: "todo",
    priority: "urgent",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_003",
      framework: "rice",
      rice: { reach: 1000, impact: 3, confidence: 85, effort: 2, score: 1275 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-15T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T08:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_004",
    teamId: "team_navigators",
    featureRequestId: "req_004",
    title: "Linear integration",
    description: "OAuth + one-click push of initiatives to Linear projects",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_003"],
    productArea: "Integrations",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_004",
      framework: "rice",
      rice: { reach: 400, impact: 2, confidence: 70, effort: 5, score: 112 },
      moscow: "should",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-22T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-22T14:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "init_005",
    teamId: "team_navigators",
    featureRequestId: "req_005",
    title: "Capacity planning bar",
    description: "Real-time capacity meter in roadmap view; over-capacity warnings",
    assignedPmId: "u_pm_01",
    goalIds: ["goal_002"],
    productArea: "Roadmap Planning",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "init_005",
      framework: "rice",
      rice: { reach: 800, impact: 2, confidence: 90, effort: 1, score: 1440 },
      moscow: "must",
      wsjf: null,
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-23T10:00:00Z",
      scoredBy: "u_pm_01",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-23T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

// ── Quarterly Plan ─────────────────────────

export const SEED_PLAN: QuarterlyPlan = {
  id: "plan_q2_2026",
  quarter: Q2_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: SEED_GOALS,
  items: SEED_INITIATIVES,
  capacity: {
    unit: "story_points",
    total: 60,
    committed: SEED_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0),
    warningThreshold: 0.9,
    byArea: {},
  },
  reviewers: [
    {
      userId: "u_eng_lead",
      name: "Jordan S.",
      email: "jordan@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
    {
      userId: "u_vp",
      name: "Morgan L.",
      email: "morgan@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
  ],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-01T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Hitchhiker team plan ───────────────────

const HITCHHIKER_GOALS: QuarterlyGoal[] = [
  {
    id: "hh_goal_001",
    title: "Platform reliability",
    description: "Achieve 99.9% uptime and reduce P1 incidents by 50%",
    owningTeam: "Hitchhikers Team",
    kpiTarget: "P1 incidents < 2 per quarter",
    weight: 5,
    quarter: Q2_2026,
    color: "#30a46c",
  },
  {
    id: "hh_goal_002",
    title: "Developer experience",
    description: "Reduce onboarding time for new engineers from 2 weeks to 3 days",
    owningTeam: "Hitchhikers Team",
    kpiTarget: "Onboarding time ≤ 3 days",
    weight: 4,
    quarter: Q2_2026,
    color: "#3b82f6",
  },
  {
    id: "hh_goal_003",
    title: "API performance",
    description: "Bring p95 API latency under 200ms across all endpoints",
    owningTeam: "Hitchhikers Team",
    kpiTarget: "p95 latency < 200ms",
    weight: 3,
    quarter: Q2_2026,
    color: "#f97316",
  },
];

const HITCHHIKER_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_init_001",
    featureRequestId: null,
    title: "Database query optimisation",
    description: "Add missing indexes, rewrite N+1 queries, enable query plan caching",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_003"],
    productArea: "Platform",
    status: "in_progress",
    priority: "urgent",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_001",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 8, jobSize: 2, score: 4 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-19T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_002",
    featureRequestId: null,
    title: "Automated incident runbooks",
    description: "Codify P1/P2 runbooks, wire into PagerDuty alerts",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001"],
    productArea: "Platform",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_002",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 9, jobSize: 3, score: 3 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-20T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-12T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_003",
    featureRequestId: null,
    title: "Internal dev tooling portal",
    description: "Unified portal for env setup, docs, and CI status per service",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_002"],
    productArea: "Developer Experience",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_003",
      framework: "wsjf",
      rice: null,
      moscow: "should",
      wsjf: { costOfDelay: 6, jobSize: 5, score: 1.2 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-21T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-14T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_004",
    featureRequestId: null,
    title: "Service mesh migration",
    description: "Migrate inter-service calls to Istio for mTLS and traffic observability",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001", "hh_goal_003"],
    productArea: "Infrastructure",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_004",
      framework: "wsjf",
      rice: null,
      moscow: "could",
      wsjf: { costOfDelay: 5, jobSize: 8, score: 0.625 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-22T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [{ initiativeId: "hh_init_001", type: "blocked_by" }],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-16T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_init_005",
    featureRequestId: null,
    title: "On-call rotation tooling",
    description: "Automate handoff notes, schedule rotations, track fatigue metrics",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_goal_001"],
    productArea: "Developer Experience",
    status: "done",
    priority: "high",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q2_2026,
    score: {
      initiativeId: "hh_init_005",
      framework: "wsjf",
      rice: null,
      moscow: "must",
      wsjf: { costOfDelay: 7, jobSize: 1, score: 7 },
      manualRankOverride: null,
      overrideReason: null,
      scoredAt: "2026-05-17T09:00:00Z",
      scoredBy: "u_pm_02",
      history: [],
    },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

const HITCHHIKER_COMMITTED = HITCHHIKER_INITIATIVES.reduce(
  (s, i) => s + (i.effort.points ?? 0),
  0,
);

export const SEED_PLAN_HITCHHIKER: QuarterlyPlan = {
  id: "plan_hh_q2_2026",
  quarter: Q2_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "in_review",
  goals: HITCHHIKER_GOALS,
  items: HITCHHIKER_INITIATIVES,
  capacity: {
    unit: "story_points",
    total: 80,
    committed: HITCHHIKER_COMMITTED,
    warningThreshold: 0.9,
    byArea: {},
  },
  reviewers: [
    {
      userId: "u_cto",
      name: "Sam Rivera",
      email: "sam@keel.so",
      required: true,
      decision: "approved",
      comment: "Looks solid. Ship it.",
      reviewedAt: "2026-05-22T14:00:00Z",
    },
    {
      userId: "u_vp_eng",
      name: "Dana Kim",
      email: "dana@keel.so",
      required: true,
      decision: null,
      comment: null,
      reviewedAt: null,
    },
  ],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-02T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q3 2026 — Navigators ────────────────────

const NAV_Q3_GOALS: QuarterlyGoal[] = [
  { id: "nav_q3_g1", title: "AI-powered triage", description: "Surface highest-signal requests automatically", owningTeam: "Navigators Team", kpiTarget: "80% auto-triaged within 24h", weight: 5, quarter: Q3_2026, color: "#5e5ce6" },
  { id: "nav_q3_g2", title: "Mobile expansion",  description: "Native mobile experience for on-the-go triage", owningTeam: "Navigators Team", kpiTarget: "iOS & Android beta shipped", weight: 4, quarter: Q3_2026, color: "#ec4899" },
  { id: "nav_q3_g3", title: "API v2 public launch", description: "Open platform to third-party integrations", owningTeam: "Navigators Team", kpiTarget: "10 external integrations live", weight: 3, quarter: Q3_2026, color: "#30a46c" },
];

const NAV_Q3_INITIATIVES: RoadmapItem[] = [
  {
    id: "nav_q3_i1",
    featureRequestId: null,
    title: "AI triage assistant",
    description: "ML model that scores incoming requests by impact and novelty",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g1"],
    productArea: "Core Product",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i1", framework: "rice", rice: { reach: 500, impact: 4, confidence: 70, effort: 8, score: 175 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q3_i2",
    featureRequestId: null,
    title: "iOS app — triage & review",
    description: "Native iOS app for triaging requests and reviewing plans on mobile",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g2"],
    productArea: "Growth",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i2", framework: "rice", rice: { reach: 800, impact: 3, confidence: 60, effort: 13, score: 111 }, moscow: "should", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q3_i3",
    featureRequestId: null,
    title: "Public API v2 — stable endpoints",
    description: "Versioned REST API with OpenAPI spec and JS/Python SDKs",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g3"],
    productArea: "Integrations",
    status: "todo",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i3", framework: "rice", rice: { reach: 300, impact: 4, confidence: 80, effort: 5, score: 192 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q3_i4",
    featureRequestId: null,
    title: "Bulk export (CSV / JSON)",
    description: "Export the full request backlog and roadmap items for reporting",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q3_g3"],
    productArea: "Core Product",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "nav_q3_i4", framework: "rice", rice: { reach: 400, impact: 2, confidence: 90, effort: 2, score: 360 }, moscow: "could", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_Q3: QuarterlyPlan = {
  id: "plan_nav_q3_2026",
  quarter: Q3_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: NAV_Q3_GOALS,
  items: NAV_Q3_INITIATIVES,
  capacity: { unit: "story_points", total: 60, committed: NAV_Q3_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q3 2026 — Hitchhiker ────────────────────

const HH_Q3_GOALS: QuarterlyGoal[] = [
  { id: "hh_q3_g1", title: "Kubernetes migration", description: "Migrate all services to K8s", owningTeam: "Hitchhikers Team", kpiTarget: "100% services on K8s by Q3 end", weight: 5, quarter: Q3_2026, color: "#3b82f6" },
  { id: "hh_q3_g2", title: "Security hardening",   description: "SOC 2 Type II readiness and zero critical CVEs", owningTeam: "Hitchhikers Team", kpiTarget: "SOC 2 audit passed", weight: 5, quarter: Q3_2026, color: "#e5484d" },
];

const HH_Q3_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_q3_i1",
    featureRequestId: null,
    title: "K8s cluster setup & service migration",
    description: "Provision production K8s cluster and migrate the top 5 services",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q3_g1"],
    productArea: "Platform",
    status: "todo",
    priority: "urgent",
    effort: { unit: "story_points", points: 34, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "hh_q3_i1", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 9, jobSize: 3, score: 3 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_q3_i2",
    featureRequestId: null,
    title: "SOC 2 Type II audit preparation",
    description: "Evidence gathering, control implementation, and external auditor engagement",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q3_g2"],
    productArea: "Platform",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "hh_q3_i2", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 10, jobSize: 4, score: 2.5 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_q3_i3",
    featureRequestId: null,
    title: "Secrets management overhaul",
    description: "Replace env-var secrets with Vault-based dynamic secrets",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q3_g2"],
    productArea: "Platform",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q3_2026,
    score: { initiativeId: "hh_q3_i3", framework: "wsjf", rice: null, moscow: "should", wsjf: { costOfDelay: 7, jobSize: 2, score: 3.5 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_HH_Q3: QuarterlyPlan = {
  id: "plan_hh_q3_2026",
  quarter: Q3_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "draft",
  goals: HH_Q3_GOALS,
  items: HH_Q3_INITIATIVES,
  capacity: { unit: "story_points", total: 80, committed: HH_Q3_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q4 2026 — Navigators ────────────────────

const NAV_Q4_GOALS: QuarterlyGoal[] = [
  { id: "nav_q4_g1", title: "Enterprise launch",   description: "Ship enterprise tier with SSO, audit log, and permissions", owningTeam: "Navigators Team", kpiTarget: "5 enterprise deals closed", weight: 5, quarter: Q4_2026, color: "#f97316" },
  { id: "nav_q4_g2", title: "Year-end retention",  description: "Reduce churn below 3% with proactive success motions", owningTeam: "Navigators Team", kpiTarget: "Monthly churn < 3%", weight: 4, quarter: Q4_2026, color: "#8b5cf6" },
];

const NAV_Q4_INITIATIVES: RoadmapItem[] = [
  {
    id: "nav_q4_i1",
    featureRequestId: null,
    title: "SSO / SAML integration",
    description: "Login via Okta, Azure AD, and Google Workspace for enterprise teams",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q4_g1"],
    productArea: "Platform",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "nav_q4_i1", framework: "rice", rice: { reach: 200, impact: 5, confidence: 85, effort: 5, score: 170 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q4_i2",
    featureRequestId: null,
    title: "Audit log & activity trail",
    description: "Immutable log of all plan changes, role assignments, and share events",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q4_g1"],
    productArea: "Platform",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 8, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "nav_q4_i2", framework: "rice", rice: { reach: 150, impact: 4, confidence: 80, effort: 3, score: 160 }, moscow: "must", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "nav_q4_i3",
    featureRequestId: null,
    title: "In-app NPS & churn signals",
    description: "Embed NPS survey and passive churn-risk detection in the product",
    assignedPmId: "u_pm_01",
    goalIds: ["nav_q4_g2"],
    productArea: "Growth",
    status: "backlog",
    priority: "medium",
    effort: { unit: "story_points", points: 5, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "nav_q4_i3", framework: "rice", rice: { reach: 1000, impact: 3, confidence: 70, effort: 2, score: 1050 }, moscow: "should", wsjf: null, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_01", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_Q4: QuarterlyPlan = {
  id: "plan_nav_q4_2026",
  quarter: Q4_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_navigators",
  status: "draft",
  goals: NAV_Q4_GOALS,
  items: NAV_Q4_INITIATIVES,
  capacity: { unit: "story_points", total: 60, committed: NAV_Q4_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};

// ── Q4 2026 — Hitchhiker ────────────────────

const HH_Q4_GOALS: QuarterlyGoal[] = [
  { id: "hh_q4_g1", title: "Observability platform", description: "Full-stack observability with distributed tracing and unified dashboards", owningTeam: "Hitchhikers Team", kpiTarget: "MTTR < 15 min for P1", weight: 5, quarter: Q4_2026, color: "#14b8a6" },
  { id: "hh_q4_g2", title: "Disaster recovery",      description: "RTO < 1h and RPO < 15min across all production services", owningTeam: "Hitchhikers Team", kpiTarget: "DR drill passes RTO < 60 min", weight: 4, quarter: Q4_2026, color: "#f97316" },
];

const HH_Q4_INITIATIVES: RoadmapItem[] = [
  {
    id: "hh_q4_i1",
    featureRequestId: null,
    title: "Distributed tracing with OpenTelemetry",
    description: "Instrument all services with OTel and route traces to Grafana Tempo",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q4_g1"],
    productArea: "Platform",
    status: "backlog",
    priority: "high",
    effort: { unit: "story_points", points: 13, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "hh_q4_i1", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 8, jobSize: 2, score: 4 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
  {
    id: "hh_q4_i2",
    featureRequestId: null,
    title: "Multi-region failover",
    description: "Active-passive multi-region setup with automated failover and health checks",
    assignedPmId: "u_pm_02",
    goalIds: ["hh_q4_g2"],
    productArea: "Platform",
    status: "backlog",
    priority: "urgent",
    effort: { unit: "story_points", points: 21, tshirt: null, weeks: null },
    quarter: Q4_2026,
    score: { initiativeId: "hh_q4_i2", framework: "wsjf", rice: null, moscow: "must", wsjf: { costOfDelay: 10, jobSize: 3, score: 3.3 }, manualRankOverride: null, overrideReason: null, scoredAt: "2026-05-20T09:00:00Z", scoredBy: "u_pm_02", history: [] },
    dependencies: [],
    jiraEpicId: null,
    linearProjectId: null,
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-05-23T09:00:00Z",
  },
];

export const SEED_PLAN_HH_Q4: QuarterlyPlan = {
  id: "plan_hh_q4_2026",
  quarter: Q4_2026,
  workspaceId: "ws_keel_demo",
  teamId: "team_hitchhiker",
  status: "draft",
  goals: HH_Q4_GOALS,
  items: HH_Q4_INITIATIVES,
  capacity: { unit: "story_points", total: 80, committed: HH_Q4_INITIATIVES.reduce((s, i) => s + (i.effort.points ?? 0), 0), warningThreshold: 0.9, byArea: {} },
  reviewers: [],
  lockedAt: null,
  lockedBy: null,
  createdAt: "2026-05-23T00:00:00Z",
  updatedAt: "2026-05-23T09:00:00Z",
  shareLink: null,
};
